// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Make.OpenApiClient.Models;
using Soenneker.Make.OpenApiClient.Templates.Public.Item.Blueprint;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Make.OpenApiClient.Templates.Public.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \templates\public\{templateUrl}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTemplateUrlItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The blueprint property</summary>
        public global::Soenneker.Make.OpenApiClient.Templates.Public.Item.Blueprint.BlueprintRequestBuilder Blueprint
        {
            get => new global::Soenneker.Make.OpenApiClient.Templates.Public.Item.Blueprint.BlueprintRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Templates.Public.Item.WithTemplateUrlItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTemplateUrlItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/templates/public/{templateUrl}{?cols%5B%5D*,templatePublicId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Templates.Public.Item.WithTemplateUrlItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTemplateUrlItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/templates/public/{templateUrl}{?cols%5B%5D*,templatePublicId*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves details of a public (approved) template with a given `publicUrl`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetTemplatesPublicByTemplateUrl200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetTemplatesPublicByTemplateUrl200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Templates.Public.Item.WithTemplateUrlItemRequestBuilder.WithTemplateUrlItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetTemplatesPublicByTemplateUrl200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Templates.Public.Item.WithTemplateUrlItemRequestBuilder.WithTemplateUrlItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.GetTemplatesPublicByTemplateUrl200Response>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.GetTemplatesPublicByTemplateUrl200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves details of a public (approved) template with a given `publicUrl`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Templates.Public.Item.WithTemplateUrlItemRequestBuilder.WithTemplateUrlItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Templates.Public.Item.WithTemplateUrlItemRequestBuilder.WithTemplateUrlItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Templates.Public.Item.WithTemplateUrlItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Make.OpenApiClient.Templates.Public.Item.WithTemplateUrlItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Make.OpenApiClient.Templates.Public.Item.WithTemplateUrlItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves details of a public (approved) template with a given `publicUrl`.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithTemplateUrlItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Specifies the group of values to return. For example, you may want to retrieve only information about the apps used in the template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cols%5B%5D")]
            public global::Soenneker.Make.OpenApiClient.Models.GetTemplatesPublicByTemplateUrlColsParameterItem[]? Cols { get; set; }
#nullable restore
#else
            [QueryParameter("cols%5B%5D")]
            public global::Soenneker.Make.OpenApiClient.Models.GetTemplatesPublicByTemplateUrlColsParameterItem[] Cols { get; set; }
#endif
            /// <summary>&quot;The unique ID of the public version of the approved template. It can be retrieved from the [List templates](/api-reference/templates/get--templates.md) endpoint as one of the following IDs: `publishedId` for all published templates that are waiting for approval or not, or `approvedId` for approved templates.&quot;</summary>
            [QueryParameter("templatePublicId")]
            public int? TemplatePublicId { get; set; }
        }
    }
}
#pragma warning restore CS0618
