// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Make.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Make.OpenApiClient.Admin.Users.Lookup
{
    /// <summary>
    /// Builds and executes requests for operations under \admin\users\lookup
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LookupRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Admin.Users.Lookup.LookupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LookupRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/users/lookup?q={q}&type={type}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Admin.Users.Lookup.LookupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LookupRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/users/lookup?q={q}&type={type}", rawUrl)
        {
        }
        /// <summary>
        /// Looks up a single user by exact numeric ID or exact email match (case-insensitive). Deleted users are always included.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetAdminUsersLookup200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetAdminUsersLookup200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Admin.Users.Lookup.LookupRequestBuilder.LookupRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetAdminUsersLookup200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Admin.Users.Lookup.LookupRequestBuilder.LookupRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.GetAdminUsersLookup200Response>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.GetAdminUsersLookup200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Looks up a single user by exact numeric ID or exact email match (case-insensitive). Deleted users are always included.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Admin.Users.Lookup.LookupRequestBuilder.LookupRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Admin.Users.Lookup.LookupRequestBuilder.LookupRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Admin.Users.Lookup.LookupRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Make.OpenApiClient.Admin.Users.Lookup.LookupRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Make.OpenApiClient.Admin.Users.Lookup.LookupRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Looks up a single user by exact numeric ID or exact email match (case-insensitive). Deleted users are always included.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LookupRequestBuilderGetQueryParameters 
        {
            /// <summary>Lookup value. Use a numeric string when `type=id` or an email address when `type=email`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("q")]
            public string? Q { get; set; }
#nullable restore
#else
            [QueryParameter("q")]
            public string Q { get; set; }
#endif
            /// <summary>Lookup strategy for the `q` value.</summary>
            [QueryParameter("type")]
            public global::Soenneker.Make.OpenApiClient.Models.GetAdminUsersLookupTypeParameter? Type { get; set; }
        }
    }
}
#pragma warning restore CS0618
