// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Make.OpenApiClient.Internal.Organizations.Item.Paused;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Make.OpenApiClient.Internal.Organizations.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \internal\organizations\{organizationId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithOrganizationItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The paused property</summary>
        public global::Soenneker.Make.OpenApiClient.Internal.Organizations.Item.Paused.PausedRequestBuilder Paused
        {
            get => new global::Soenneker.Make.OpenApiClient.Internal.Organizations.Item.Paused.PausedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Internal.Organizations.Item.WithOrganizationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOrganizationItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/internal/organizations/{organizationId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Internal.Organizations.Item.WithOrganizationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOrganizationItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/internal/organizations/{organizationId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
