// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Make.OpenApiClient.Models;
using Soenneker.Make.OpenApiClient.Sdk.Apps.Connections;
using Soenneker.Make.OpenApiClient.Sdk.Apps.Invites;
using Soenneker.Make.OpenApiClient.Sdk.Apps.Item;
using Soenneker.Make.OpenApiClient.Sdk.Apps.Themes;
using Soenneker.Make.OpenApiClient.Sdk.Apps.Webhooks;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Make.OpenApiClient.Sdk.Apps
{
    /// <summary>
    /// Builds and executes requests for operations under \sdk\apps
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AppsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The connections property</summary>
        public global::Soenneker.Make.OpenApiClient.Sdk.Apps.Connections.ConnectionsRequestBuilder Connections
        {
            get => new global::Soenneker.Make.OpenApiClient.Sdk.Apps.Connections.ConnectionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The invites property</summary>
        public global::Soenneker.Make.OpenApiClient.Sdk.Apps.Invites.InvitesRequestBuilder Invites
        {
            get => new global::Soenneker.Make.OpenApiClient.Sdk.Apps.Invites.InvitesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The themes property</summary>
        public global::Soenneker.Make.OpenApiClient.Sdk.Apps.Themes.ThemesRequestBuilder Themes
        {
            get => new global::Soenneker.Make.OpenApiClient.Sdk.Apps.Themes.ThemesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::Soenneker.Make.OpenApiClient.Sdk.Apps.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::Soenneker.Make.OpenApiClient.Sdk.Apps.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Make.OpenApiClient.sdk.apps.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Sdk.Apps.Item.WithSdkAppNameItemRequestBuilder"/></returns>
        public global::Soenneker.Make.OpenApiClient.Sdk.Apps.Item.WithSdkAppNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("sdkAppName", position);
                return new global::Soenneker.Make.OpenApiClient.Sdk.Apps.Item.WithSdkAppNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Sdk.Apps.AppsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AppsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Sdk.Apps.AppsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AppsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves a collection of all apps available to the authenticated user.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetSdkApps200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetSdkApps200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Sdk.Apps.AppsRequestBuilder.AppsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetSdkApps200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Sdk.Apps.AppsRequestBuilder.AppsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.GetSdkApps200Response>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.GetSdkApps200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new app with data passed in the request body. In the response, it returns all details of the created app.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.PostSdkApps200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.PostSdkApps200Response?> PostAsync(global::Soenneker.Make.OpenApiClient.Models.PostSdkAppsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.PostSdkApps200Response> PostAsync(global::Soenneker.Make.OpenApiClient.Models.PostSdkAppsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.PostSdkApps200Response>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.PostSdkApps200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves a collection of all apps available to the authenticated user.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Sdk.Apps.AppsRequestBuilder.AppsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Sdk.Apps.AppsRequestBuilder.AppsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new app with data passed in the request body. In the response, it returns all details of the created app.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Make.OpenApiClient.Models.PostSdkAppsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Make.OpenApiClient.Models.PostSdkAppsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Sdk.Apps.AppsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Make.OpenApiClient.Sdk.Apps.AppsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Make.OpenApiClient.Sdk.Apps.AppsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves a collection of all apps available to the authenticated user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AppsRequestBuilderGetQueryParameters 
        {
            /// <summary>Specifies the group of values to return. For example, you may want to retrieve only the names of the available apps.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cols%5B%5D")]
            public global::Soenneker.Make.OpenApiClient.Models.GetSdkAppsColsParameterItem[]? Cols { get; set; }
#nullable restore
#else
            [QueryParameter("cols%5B%5D")]
            public global::Soenneker.Make.OpenApiClient.Models.GetSdkAppsColsParameterItem[] Cols { get; set; }
#endif
            /// <summary>If set to `true`, this parameter returns apps available to all users. If set to `false`, it retrieves the apps available to the authenticated user.</summary>
            [QueryParameter("opensource")]
            public bool? Opensource { get; set; }
        }
    }
}
#pragma warning restore CS0618
