// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Make.OpenApiClient.Organizations.Item.Domains.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Make.OpenApiClient.Organizations.Item.Domains
{
    /// <summary>
    /// Builds and executes requests for operations under \organizations\{organizationId}\domains
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DomainsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Make.OpenApiClient.organizations.item.domains.item collection</summary>
        /// <param name="position">The ID of the organization domain.</param>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Organizations.Item.Domains.Item.WithOrganizationDomainItemRequestBuilder"/></returns>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.Domains.Item.WithOrganizationDomainItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("organizationDomainId", position);
                return new global::Soenneker.Make.OpenApiClient.Organizations.Item.Domains.Item.WithOrganizationDomainItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Organizations.Item.Domains.DomainsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DomainsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organizations/{organizationId}/domains", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Organizations.Item.Domains.DomainsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DomainsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organizations/{organizationId}/domains", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
