// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Make.OpenApiClient.Models;
using Soenneker.Make.OpenApiClient.Scenarios.Item.Data.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Make.OpenApiClient.Scenarios.Item.Data
{
    /// <summary>
    /// Builds and executes requests for operations under \scenarios\{scenarioId}\data
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DataRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Make.OpenApiClient.scenarios.item.data.item collection</summary>
        /// <param name="position">The unique ID of the scenario module. It is available in the scenario blueprint that can be retrieved from the [Get scenario blueprint](/api-reference/scenarios/blueprint/get--scenarios--scenarioid--blueprint.md) endpoint.</param>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Scenarios.Item.Data.Item.WithModuleItemRequestBuilder"/></returns>
        public global::Soenneker.Make.OpenApiClient.Scenarios.Item.Data.Item.WithModuleItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("moduleId", position);
                return new global::Soenneker.Make.OpenApiClient.Scenarios.Item.Data.Item.WithModuleItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Scenarios.Item.Data.DataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DataRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/scenarios/{scenarioId}/data", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Scenarios.Item.Data.DataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DataRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/scenarios/{scenarioId}/data", rawUrl)
        {
        }
        /// <summary>
        /// **Why the docs are internal:**It&apos;s not clear how to use this EP. The example suggest that the EP can only change the trigger epoch.But the EP&apos;s SQL routine and original documentation suggest that the EP is supposed to update any module.I wasn&apos;t able to reproduce that use case even with the simplest modules. Furthermore, the EP always returns successful response, even though it didn&apos;t update anything.This causes a lot of confusion and frustration ot the users. So until the usage of the EP is clear the docs should be hidden.2023-06-06, agreed with Ondrej Vesely.**Original docs:**Sets the module data for a scenario with a given ID by passing new values in the request body. It replaces the entire resource with the new values. In the response, it returns the confirmation if the scenario was updated.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.PutScenariosScenarioIdData200"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.PutScenariosScenarioIdData200?> PutAsync(global::Soenneker.Make.OpenApiClient.Scenarios.Item.Data.DataPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.PutScenariosScenarioIdData200> PutAsync(global::Soenneker.Make.OpenApiClient.Scenarios.Item.Data.DataPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.PutScenariosScenarioIdData200>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.PutScenariosScenarioIdData200.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// **Why the docs are internal:**It&apos;s not clear how to use this EP. The example suggest that the EP can only change the trigger epoch.But the EP&apos;s SQL routine and original documentation suggest that the EP is supposed to update any module.I wasn&apos;t able to reproduce that use case even with the simplest modules. Furthermore, the EP always returns successful response, even though it didn&apos;t update anything.This causes a lot of confusion and frustration ot the users. So until the usage of the EP is clear the docs should be hidden.2023-06-06, agreed with Ondrej Vesely.**Original docs:**Sets the module data for a scenario with a given ID by passing new values in the request body. It replaces the entire resource with the new values. In the response, it returns the confirmation if the scenario was updated.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Make.OpenApiClient.Scenarios.Item.Data.DataPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Make.OpenApiClient.Scenarios.Item.Data.DataPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Scenarios.Item.Data.DataRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Make.OpenApiClient.Scenarios.Item.Data.DataRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Make.OpenApiClient.Scenarios.Item.Data.DataRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
