// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Make.OpenApiClient.Models;
using Soenneker.Make.OpenApiClient.Sdk.Apps.Item.Item.AppReview.Cancel;
using Soenneker.Make.OpenApiClient.Sdk.Apps.Item.Item.AppReview.Form;
using Soenneker.Make.OpenApiClient.Sdk.Apps.Item.Item.AppReview.Start;
using Soenneker.Make.OpenApiClient.Sdk.Apps.Item.Item.AppReview.Submit;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Make.OpenApiClient.Sdk.Apps.Item.Item.AppReview
{
    /// <summary>
    /// Builds and executes requests for operations under \sdk\apps\{sdkAppName}\{sdkAppVersion}\app-review
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AppReviewRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cancel property</summary>
        public global::Soenneker.Make.OpenApiClient.Sdk.Apps.Item.Item.AppReview.Cancel.CancelRequestBuilder Cancel
        {
            get => new global::Soenneker.Make.OpenApiClient.Sdk.Apps.Item.Item.AppReview.Cancel.CancelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The form property</summary>
        public global::Soenneker.Make.OpenApiClient.Sdk.Apps.Item.Item.AppReview.Form.FormRequestBuilder Form
        {
            get => new global::Soenneker.Make.OpenApiClient.Sdk.Apps.Item.Item.AppReview.Form.FormRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The start property</summary>
        public global::Soenneker.Make.OpenApiClient.Sdk.Apps.Item.Item.AppReview.Start.StartRequestBuilder Start
        {
            get => new global::Soenneker.Make.OpenApiClient.Sdk.Apps.Item.Item.AppReview.Start.StartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The submit property</summary>
        public global::Soenneker.Make.OpenApiClient.Sdk.Apps.Item.Item.AppReview.Submit.SubmitRequestBuilder Submit
        {
            get => new global::Soenneker.Make.OpenApiClient.Sdk.Apps.Item.Item.AppReview.Submit.SubmitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Sdk.Apps.Item.Item.AppReview.AppReviewRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AppReviewRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sdk/apps/{sdkAppName}/{sdkAppVersion}/app-review", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Sdk.Apps.Item.Item.AppReview.AppReviewRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AppReviewRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sdk/apps/{sdkAppName}/{sdkAppVersion}/app-review", rawUrl)
        {
        }
        /// <summary>
        /// Returns the full state of the new review flow for the app version: the lifecycle phase, the auto-saved draft form, the submitted snapshot, and the review history timeline. Always responds `200` for the app&apos;s author — when the new flow has never touched the app, the state is synthesized (`derivedFromLegacy: true`) from the legacy review flags: an approved app reports `approved`, an in-review app reports `review` (or `changes_required` when the legacy reviewer status is &quot;feedback sent&quot;), anything else reports `dormant`. Only the app&apos;s author (or an administrator) may read the review state. Available only while the `is_sdk_app_review_enabled` feature flag is on, otherwise responds with `400` (IM903).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetSdkAppsBySdkAppNameBySdkAppVersionAppReview200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetSdkAppsBySdkAppNameBySdkAppVersionAppReview200Response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetSdkAppsBySdkAppNameBySdkAppVersionAppReview200Response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.GetSdkAppsBySdkAppNameBySdkAppVersionAppReview200Response>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.GetSdkAppsBySdkAppNameBySdkAppVersionAppReview200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the full state of the new review flow for the app version: the lifecycle phase, the auto-saved draft form, the submitted snapshot, and the review history timeline. Always responds `200` for the app&apos;s author — when the new flow has never touched the app, the state is synthesized (`derivedFromLegacy: true`) from the legacy review flags: an approved app reports `approved`, an in-review app reports `review` (or `changes_required` when the legacy reviewer status is &quot;feedback sent&quot;), anything else reports `dormant`. Only the app&apos;s author (or an administrator) may read the review state. Available only while the `is_sdk_app_review_enabled` feature flag is on, otherwise responds with `400` (IM903).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Sdk.Apps.Item.Item.AppReview.AppReviewRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Make.OpenApiClient.Sdk.Apps.Item.Item.AppReview.AppReviewRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Make.OpenApiClient.Sdk.Apps.Item.Item.AppReview.AppReviewRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
