// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Make.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Make.OpenApiClient.ImtForms.Endpoints.Item.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \imt-forms\endpoints\{app}\{version}\{endpoint}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithEndpointItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.ImtForms.Endpoints.Item.Item.Item.WithEndpointItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEndpointItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/imt-forms/endpoints/{app}/{version}/{endpoint}?teamId={teamId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.ImtForms.Endpoints.Item.Item.Item.WithEndpointItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEndpointItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/imt-forms/endpoints/{app}/{version}/{endpoint}?teamId={teamId}", rawUrl)
        {
        }
        /// <summary>
        /// Returns an IMT Form for testing an SDK (`app#name`) or native app Endpoint.Requires TEAM_VIEW for the supplied team (ORGANIZATION_VIEW for admin requests),runtime app access for SDK apps, and the endpoint-execution feature flag.Native endpoints are resolved directly, including private and deprecated definitions.SDK authors see pending input, attached-account and scope edits; other callers see published values.The required `connectionId` account field is omitted when there are no attached accounts.Its `options.scope` maps each resolved account type (including SDK aliases) to that endpoint&apos;srequired OAuth scopes. Native account types can require different scopes. Connection-defaultscope injection remains in the existing connection backend flow.`input.spec` contains the endpoint input fields, expanded from JSON Schema where supported,and is always present, including when empty. Hidden fields preserve the execution coordinatesand authorized team. Version lookup and submission use the numeric major version.The Test button submits the complete JSON values directly to POST /endpoints/execute,without an RPC data wrapper. The response omits multipart because this form uses JSON.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetEndpointInputForm200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetEndpointInputForm200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.ImtForms.Endpoints.Item.Item.Item.WithEndpointItemRequestBuilder.WithEndpointItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetEndpointInputForm200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.ImtForms.Endpoints.Item.Item.Item.WithEndpointItemRequestBuilder.WithEndpointItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.GetEndpointInputForm200Response>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.GetEndpointInputForm200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns an IMT Form for testing an SDK (`app#name`) or native app Endpoint.Requires TEAM_VIEW for the supplied team (ORGANIZATION_VIEW for admin requests),runtime app access for SDK apps, and the endpoint-execution feature flag.Native endpoints are resolved directly, including private and deprecated definitions.SDK authors see pending input, attached-account and scope edits; other callers see published values.The required `connectionId` account field is omitted when there are no attached accounts.Its `options.scope` maps each resolved account type (including SDK aliases) to that endpoint&apos;srequired OAuth scopes. Native account types can require different scopes. Connection-defaultscope injection remains in the existing connection backend flow.`input.spec` contains the endpoint input fields, expanded from JSON Schema where supported,and is always present, including when empty. Hidden fields preserve the execution coordinatesand authorized team. Version lookup and submission use the numeric major version.The Test button submits the complete JSON values directly to POST /endpoints/execute,without an RPC data wrapper. The response omits multipart because this form uses JSON.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.ImtForms.Endpoints.Item.Item.Item.WithEndpointItemRequestBuilder.WithEndpointItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.ImtForms.Endpoints.Item.Item.Item.WithEndpointItemRequestBuilder.WithEndpointItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.ImtForms.Endpoints.Item.Item.Item.WithEndpointItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Make.OpenApiClient.ImtForms.Endpoints.Item.Item.Item.WithEndpointItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Make.OpenApiClient.ImtForms.Endpoints.Item.Item.Item.WithEndpointItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns an IMT Form for testing an SDK (`app#name`) or native app Endpoint.Requires TEAM_VIEW for the supplied team (ORGANIZATION_VIEW for admin requests),runtime app access for SDK apps, and the endpoint-execution feature flag.Native endpoints are resolved directly, including private and deprecated definitions.SDK authors see pending input, attached-account and scope edits; other callers see published values.The required `connectionId` account field is omitted when there are no attached accounts.Its `options.scope` maps each resolved account type (including SDK aliases) to that endpoint&apos;srequired OAuth scopes. Native account types can require different scopes. Connection-defaultscope injection remains in the existing connection backend flow.`input.spec` contains the endpoint input fields, expanded from JSON Schema where supported,and is always present, including when empty. Hidden fields preserve the execution coordinatesand authorized team. Version lookup and submission use the numeric major version.The Test button submits the complete JSON values directly to POST /endpoints/execute,without an RPC data wrapper. The response omits multipart because this form uses JSON.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithEndpointItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Team authorized for the subsequent execution.</summary>
            [QueryParameter("teamId")]
            public int? TeamId { get; set; }
        }
    }
}
#pragma warning restore CS0618
