// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Make.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Make.OpenApiClient.Admin.Apps.Item.InstallationHistory
{
    /// <summary>
    /// Builds and executes requests for operations under \admin\apps\{app}\installation-history
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InstallationHistoryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Admin.Apps.Item.InstallationHistory.InstallationHistoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InstallationHistoryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/apps/{app}/installation-history{?pg%5Blimit%5D*,pg%5Boffset%5D*,pg%5BreturnTotalCount%5D*,pg%5BsortBy%5D*,pg%5BsortDir%5D*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Admin.Apps.Item.InstallationHistory.InstallationHistoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InstallationHistoryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/apps/{app}/installation-history{?pg%5Blimit%5D*,pg%5Boffset%5D*,pg%5BreturnTotalCount%5D*,pg%5BsortBy%5D*,pg%5BsortDir%5D*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns the recorded installation attempt history for a single native app, ordered by most recent first.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetAdminAppsByAppInstallationHistory200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Make.OpenApiClient.Models.GetAdminAppsByAppInstallationHistory400Response">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetAdminAppsByAppInstallationHistory200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Admin.Apps.Item.InstallationHistory.InstallationHistoryRequestBuilder.InstallationHistoryRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetAdminAppsByAppInstallationHistory200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Admin.Apps.Item.InstallationHistory.InstallationHistoryRequestBuilder.InstallationHistoryRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Make.OpenApiClient.Models.GetAdminAppsByAppInstallationHistory400Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.GetAdminAppsByAppInstallationHistory200Response>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.GetAdminAppsByAppInstallationHistory200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the recorded installation attempt history for a single native app, ordered by most recent first.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Admin.Apps.Item.InstallationHistory.InstallationHistoryRequestBuilder.InstallationHistoryRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Admin.Apps.Item.InstallationHistory.InstallationHistoryRequestBuilder.InstallationHistoryRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Admin.Apps.Item.InstallationHistory.InstallationHistoryRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Make.OpenApiClient.Admin.Apps.Item.InstallationHistory.InstallationHistoryRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Make.OpenApiClient.Admin.Apps.Item.InstallationHistory.InstallationHistoryRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns the recorded installation attempt history for a single native app, ordered by most recent first.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InstallationHistoryRequestBuilderGetQueryParameters 
        {
            /// <summary>Page size (max 1000).</summary>
            [QueryParameter("pg%5Blimit%5D")]
            public int? Pglimit { get; set; }
            /// <summary>Number of records to skip.</summary>
            [QueryParameter("pg%5Boffset%5D")]
            public int? Pgoffset { get; set; }
            /// <summary>When true, the response pagination block contains the total record count. This option is supported only for session (cookie) authentication. Token-authenticated requests that send `pg[returnTotalCount]=true` are rejected with HTTP 400.</summary>
            [QueryParameter("pg%5BreturnTotalCount%5D")]
            public bool? PgreturnTotalCount { get; set; }
            /// <summary>Field to sort by.</summary>
            [QueryParameter("pg%5BsortBy%5D")]
            public global::Soenneker.Make.OpenApiClient.Models.GetAdminAppsByAppInstallationHistoryPgSortByParameter? PgsortBy { get; set; }
            /// <summary>Sort direction.</summary>
            [QueryParameter("pg%5BsortDir%5D")]
            public global::Soenneker.Make.OpenApiClient.Models.GetAdminAppsByAppInstallationHistoryPgSortDirParameter? PgsortDir { get; set; }
        }
    }
}
#pragma warning restore CS0618
