// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Make.OpenApiClient.Models;
using Soenneker.Make.OpenApiClient.ScenariosFolders.Item;
using Soenneker.Make.OpenApiClient.ScenariosFolders.MoveScenarios;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Make.OpenApiClient.ScenariosFolders
{
    /// <summary>
    /// Builds and executes requests for operations under \scenarios-folders
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ScenariosFoldersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The moveScenarios property</summary>
        public global::Soenneker.Make.OpenApiClient.ScenariosFolders.MoveScenarios.MoveScenariosRequestBuilder MoveScenarios
        {
            get => new global::Soenneker.Make.OpenApiClient.ScenariosFolders.MoveScenarios.MoveScenariosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Make.OpenApiClient.scenariosFolders.item collection</summary>
        /// <param name="position">The unique ID of the scenario folder. It can be retrieved from the [List scenarios folders](/api-reference/scenarios-folders/get--scenarios-folders.md) endpoint.</param>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.ScenariosFolders.Item.WithFolderItemRequestBuilder"/></returns>
        public global::Soenneker.Make.OpenApiClient.ScenariosFolders.Item.WithFolderItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("folderId", position);
                return new global::Soenneker.Make.OpenApiClient.ScenariosFolders.Item.WithFolderItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.ScenariosFolders.ScenariosFoldersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScenariosFoldersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/scenarios-folders{?cols%5B%5D*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.ScenariosFolders.ScenariosFoldersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScenariosFoldersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/scenarios-folders{?cols%5B%5D*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves a collection of all scenarios folders for a team with a given ID. Returned folders are sorted by name in ascending order.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetScenariosFolders200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetScenariosFolders200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.ScenariosFolders.ScenariosFoldersRequestBuilder.ScenariosFoldersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetScenariosFolders200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.ScenariosFolders.ScenariosFoldersRequestBuilder.ScenariosFoldersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.GetScenariosFolders200Response>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.GetScenariosFolders200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new scenario folder with data passed in the request body. As the response, it returns all details of the created scenario folder.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.PostScenariosFolders200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.PostScenariosFolders200Response?> PostAsync(global::Soenneker.Make.OpenApiClient.Models.PostScenariosFoldersRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.PostScenariosFolders200Response> PostAsync(global::Soenneker.Make.OpenApiClient.Models.PostScenariosFoldersRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.PostScenariosFolders200Response>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.PostScenariosFolders200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves a collection of all scenarios folders for a team with a given ID. Returned folders are sorted by name in ascending order.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.ScenariosFolders.ScenariosFoldersRequestBuilder.ScenariosFoldersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.ScenariosFolders.ScenariosFoldersRequestBuilder.ScenariosFoldersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, "{+baseurl}/scenarios-folders?teamId={teamId}{&cols%5B%5D*}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new scenario folder with data passed in the request body. As the response, it returns all details of the created scenario folder.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Make.OpenApiClient.Models.PostScenariosFoldersRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Make.OpenApiClient.Models.PostScenariosFoldersRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.ScenariosFolders.ScenariosFoldersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Make.OpenApiClient.ScenariosFolders.ScenariosFoldersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Make.OpenApiClient.ScenariosFolders.ScenariosFoldersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves a collection of all scenarios folders for a team with a given ID. Returned folders are sorted by name in ascending order.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ScenariosFoldersRequestBuilderGetQueryParameters 
        {
            /// <summary>Specifies the group of values to return. For example, you may want to receive in response only the names and IDs of folders.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cols%5B%5D")]
            public global::Soenneker.Make.OpenApiClient.Models.GetScenariosFoldersColsParameterItem[]? Cols { get; set; }
#nullable restore
#else
            [QueryParameter("cols%5B%5D")]
            public global::Soenneker.Make.OpenApiClient.Models.GetScenariosFoldersColsParameterItem[] Cols { get; set; }
#endif
            /// <summary>Unique ID of the Team.</summary>
            [QueryParameter("teamId")]
            public int? TeamId { get; set; }
        }
    }
}
#pragma warning restore CS0618
