// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Make.OpenApiClient.Notifications
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetPgSortByQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
    }
}
