// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Make.OpenApiClient.Dlqs.Item;
using Soenneker.Make.OpenApiClient.Dlqs.Retry;
using Soenneker.Make.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Make.OpenApiClient.Dlqs
{
    /// <summary>
    /// Builds and executes requests for operations under \dlqs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DlqsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The retry property</summary>
        public global::Soenneker.Make.OpenApiClient.Dlqs.Retry.RetryRequestBuilder Retry
        {
            get => new global::Soenneker.Make.OpenApiClient.Dlqs.Retry.RetryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Make.OpenApiClient.dlqs.item collection</summary>
        /// <param name="position">The ID of the incomplete execution. Get the ID values of the incomplete executions of a scenario with the API call `GET /dlqs?scenarioId={scenarioId}`.</param>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Dlqs.Item.WithDlqItemRequestBuilder"/></returns>
        public global::Soenneker.Make.OpenApiClient.Dlqs.Item.WithDlqItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("dlqId", position);
                return new global::Soenneker.Make.OpenApiClient.Dlqs.Item.WithDlqItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Dlqs.DlqsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DlqsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/dlqs?scenarioId={scenarioId}{&attemptsFrom*,attemptsTo*,confirmed*,createdFrom*,createdTo*,idSearch*,scheduledInFrom*,scheduledInTo*,sizeFrom*,sizeTo*,status*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Dlqs.DlqsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DlqsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/dlqs?scenarioId={scenarioId}{&attemptsFrom*,attemptsTo*,confirmed*,createdFrom*,createdTo*,idSearch*,scheduledInFrom*,scheduledInTo*,sizeFrom*,sizeTo*,status*}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;Deletes incomplete executions of the specified scenario. Specify the incomplete execution ID values in the `ids` array in the request body to delete the specified incomplete executions.You can set the `\&quot;all\&quot;: true` pair to delete all incomplete executions of the specified scenario. If you use the `\&quot;all\&quot;: true` parameter, you have to specify the `confirmed=true` query parameter to confirm the deletion. Otherwise, the API call returns the error IM004 (406).Add the `exceptIds` array to the request body to specify items you don&apos;t want to delete.You get an error if you try to delete incomplete executions which are being processed. The rest of the specified items is still deleted.&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.DeleteDlqs200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.DeleteDlqs200Response?> DeleteAsync(global::Soenneker.Make.OpenApiClient.Models.DeleteDlqsRequest body, Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Dlqs.DlqsRequestBuilder.DlqsRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.DeleteDlqs200Response> DeleteAsync(global::Soenneker.Make.OpenApiClient.Models.DeleteDlqsRequest body, Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Dlqs.DlqsRequestBuilder.DlqsRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToDeleteRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.DeleteDlqs200Response>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.DeleteDlqs200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves the list of incomplete executions of the specified scenario. Supports optional server-side filters — combine any of them to narrow down the results.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetDlqs200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetDlqs200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Dlqs.DlqsRequestBuilder.DlqsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetDlqs200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Dlqs.DlqsRequestBuilder.DlqsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.GetDlqs200Response>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.GetDlqs200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Deletes incomplete executions of the specified scenario. Specify the incomplete execution ID values in the `ids` array in the request body to delete the specified incomplete executions.You can set the `\&quot;all\&quot;: true` pair to delete all incomplete executions of the specified scenario. If you use the `\&quot;all\&quot;: true` parameter, you have to specify the `confirmed=true` query parameter to confirm the deletion. Otherwise, the API call returns the error IM004 (406).Add the `exceptIds` array to the request body to specify items you don&apos;t want to delete.You get an error if you try to delete incomplete executions which are being processed. The rest of the specified items is still deleted.&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(global::Soenneker.Make.OpenApiClient.Models.DeleteDlqsRequest body, Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Dlqs.DlqsRequestBuilder.DlqsRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(global::Soenneker.Make.OpenApiClient.Models.DeleteDlqsRequest body, Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Dlqs.DlqsRequestBuilder.DlqsRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Retrieves the list of incomplete executions of the specified scenario. Supports optional server-side filters — combine any of them to narrow down the results.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Dlqs.DlqsRequestBuilder.DlqsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Dlqs.DlqsRequestBuilder.DlqsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Dlqs.DlqsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Make.OpenApiClient.Dlqs.DlqsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Make.OpenApiClient.Dlqs.DlqsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &quot;Deletes incomplete executions of the specified scenario. Specify the incomplete execution ID values in the `ids` array in the request body to delete the specified incomplete executions.You can set the `\&quot;all\&quot;: true` pair to delete all incomplete executions of the specified scenario. If you use the `\&quot;all\&quot;: true` parameter, you have to specify the `confirmed=true` query parameter to confirm the deletion. Otherwise, the API call returns the error IM004 (406).Add the `exceptIds` array to the request body to specify items you don&apos;t want to delete.You get an error if you try to delete incomplete executions which are being processed. The rest of the specified items is still deleted.&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DlqsRequestBuilderDeleteQueryParameters 
        {
            /// <summary>Set to `true` to confirm deleting the incomplete executions. Otherwise the API call fails with the error IM004 (406).</summary>
            [QueryParameter("confirmed")]
            public bool? Confirmed { get; set; }
            /// <summary>The ID value of the scenario. Use the API call `GET /scenarios` to get the ID of the scenario. If your scenario is placed in a folder, use the API call `GET /scenarios-folders?teamId={teamId}` first.</summary>
            [QueryParameter("scenarioId")]
            public int? ScenarioId { get; set; }
        }
        /// <summary>
        /// Retrieves the list of incomplete executions of the specified scenario. Supports optional server-side filters — combine any of them to narrow down the results.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DlqsRequestBuilderGetQueryParameters 
        {
            /// <summary>Filters the incomplete executions with a number of retry attempts greater than or equal to this value.</summary>
            [QueryParameter("attemptsFrom")]
            public int? AttemptsFrom { get; set; }
            /// <summary>Filters the incomplete executions with a number of retry attempts less than or equal to this value.</summary>
            [QueryParameter("attemptsTo")]
            public int? AttemptsTo { get; set; }
            /// <summary>Filters the incomplete executions created on or after this Unix timestamp (in milliseconds).</summary>
            [QueryParameter("createdFrom")]
            public int? CreatedFrom { get; set; }
            /// <summary>Filters the incomplete executions created on or before this Unix timestamp (in milliseconds).</summary>
            [QueryParameter("createdTo")]
            public int? CreatedTo { get; set; }
            /// <summary>Filters the incomplete executions by a substring of their ID value (case-insensitive).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("idSearch")]
            public string? IdSearch { get; set; }
#nullable restore
#else
            [QueryParameter("idSearch")]
            public string IdSearch { get; set; }
#endif
            /// <summary>The ID value of the scenario. Use the API call `GET /scenarios` to get the ID of the scenario. If your scenario is placed in a folder, use the API call `GET /scenarios-folders?teamId={teamId}` first.</summary>
            [QueryParameter("scenarioId")]
            public int? ScenarioId { get; set; }
            /// <summary>Filters the incomplete executions with the next automatic retry scheduled on or after this Unix timestamp (in milliseconds).</summary>
            [QueryParameter("scheduledInFrom")]
            public int? ScheduledInFrom { get; set; }
            /// <summary>Filters the incomplete executions with the next automatic retry scheduled on or before this Unix timestamp (in milliseconds).</summary>
            [QueryParameter("scheduledInTo")]
            public int? ScheduledInTo { get; set; }
            /// <summary>Filters the incomplete executions with a payload size (in bytes) greater than or equal to this value.</summary>
            [QueryParameter("sizeFrom")]
            public int? SizeFrom { get; set; }
            /// <summary>Filters the incomplete executions with a payload size (in bytes) less than or equal to this value.</summary>
            [QueryParameter("sizeTo")]
            public int? SizeTo { get; set; }
            /// <summary>&quot;Filters the incomplete executions by their derived status: `resolved` (already retried successfully), `scheduled` (will be automatically retried in the future), `inprogress` (currently being retried), or `unresolved` (none of the above).&quot;</summary>
            [QueryParameter("status")]
            public global::Soenneker.Make.OpenApiClient.Models.GetDlqsStatusParameter? Status { get; set; }
        }
    }
}
#pragma warning restore CS0618
