// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetAdminUsersDetailColsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "language")]
        #pragma warning disable CS1591
        Language,
        #pragma warning restore CS1591
        [EnumMember(Value = "timezoneId")]
        #pragma warning disable CS1591
        TimezoneId,
        #pragma warning restore CS1591
        [EnumMember(Value = "localeId")]
        #pragma warning disable CS1591
        LocaleId,
        #pragma warning restore CS1591
        [EnumMember(Value = "countryId")]
        #pragma warning disable CS1591
        CountryId,
        #pragma warning restore CS1591
        [EnumMember(Value = "features")]
        #pragma warning disable CS1591
        Features,
        #pragma warning restore CS1591
        [EnumMember(Value = "avatar")]
        #pragma warning disable CS1591
        Avatar,
        #pragma warning restore CS1591
        [EnumMember(Value = "lastLogin")]
        #pragma warning disable CS1591
        LastLogin,
        #pragma warning restore CS1591
        [EnumMember(Value = "organizations")]
        #pragma warning disable CS1591
        Organizations,
        #pragma warning restore CS1591
        [EnumMember(Value = "scenarios")]
        #pragma warning disable CS1591
        Scenarios,
        #pragma warning restore CS1591
        [EnumMember(Value = "activeScenarios")]
        #pragma warning disable CS1591
        ActiveScenarios,
        #pragma warning restore CS1591
        [EnumMember(Value = "deleted")]
        #pragma warning disable CS1591
        Deleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "created")]
        #pragma warning disable CS1591
        Created,
        #pragma warning restore CS1591
        [EnumMember(Value = "usersAdminsRoleId")]
        #pragma warning disable CS1591
        UsersAdminsRoleId,
        #pragma warning restore CS1591
        [EnumMember(Value = "tfaEnabled")]
        #pragma warning disable CS1591
        TfaEnabled,
        #pragma warning restore CS1591
    }
}
