// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetAdminUsersByUserIdAffiliateCommissions200ResponseCommisionsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The commission property</summary>
        public double? Commission { get; set; }
        /// <summary>The created property</summary>
        public DateTimeOffset? Created { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The organization_id property</summary>
        public int? OrganizationId { get; set; }
        /// <summary>The payout_approved property</summary>
        public DateTimeOffset? PayoutApproved { get; set; }
        /// <summary>The payout_realized property</summary>
        public DateTimeOffset? PayoutRealized { get; set; }
        /// <summary>The payout_requested property</summary>
        public DateTimeOffset? PayoutRequested { get; set; }
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Models.GetAdminUsersByUserIdAffiliateCommissions200ResponseCommisionsItem"/> and sets the default values.
        /// </summary>
        public GetAdminUsersByUserIdAffiliateCommissions200ResponseCommisionsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetAdminUsersByUserIdAffiliateCommissions200ResponseCommisionsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Make.OpenApiClient.Models.GetAdminUsersByUserIdAffiliateCommissions200ResponseCommisionsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Make.OpenApiClient.Models.GetAdminUsersByUserIdAffiliateCommissions200ResponseCommisionsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "commission", n => { Commission = n.GetDoubleValue(); } },
                { "created", n => { Created = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "organization_id", n => { OrganizationId = n.GetIntValue(); } },
                { "payout_approved", n => { PayoutApproved = n.GetDateTimeOffsetValue(); } },
                { "payout_realized", n => { PayoutRealized = n.GetDateTimeOffsetValue(); } },
                { "payout_requested", n => { PayoutRequested = n.GetDateTimeOffsetValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("commission", Commission);
            writer.WriteDateTimeOffsetValue("created", Created);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("organization_id", OrganizationId);
            writer.WriteDateTimeOffsetValue("payout_approved", PayoutApproved);
            writer.WriteDateTimeOffsetValue("payout_realized", PayoutRealized);
            writer.WriteDateTimeOffsetValue("payout_requested", PayoutRequested);
            writer.WriteStringValue("source", Source);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
