// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    /// <summary>The management type of the admin role.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetAdminUsersAdminsRoles200ResponseUsersAdminsRolesItemManagementType
    {
        [EnumMember(Value = "admin_managed")]
        #pragma warning disable CS1591
        AdminManaged,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_managed")]
        #pragma warning disable CS1591
        CustomManaged,
        #pragma warning restore CS1591
        [EnumMember(Value = "system_locked")]
        #pragma warning disable CS1591
        SystemLocked,
        #pragma warning restore CS1591
    }
}
