// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetImtAppsMeta200ResponseAppsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>true for custom apps - either private or installed from an invite link, false for verified apps</summary>
        public bool? App { get; set; }
        /// <summary>The brand property</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Make.OpenApiClient.Models.GetImtAppsMeta200ResponseAppsItemBrand? Brand { get; set; }
#nullable restore
#else
        public global::Soenneker.Make.OpenApiClient.Models.GetImtAppsMeta200ResponseAppsItemBrand Brand { get; set; }
#endif
        /// <summary>array of strings [&apos;category1&apos;, &apos;category2&apos;], NOT YET IMPLEMENTED</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Categories { get; set; }
#nullable restore
#else
        public List<string> Categories { get; set; }
#endif
        /// <summary>The coming_soon property</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Make.OpenApiClient.Models.GetImtAppsMeta200ResponseAppsItemComingSoon? ComingSoon { get; set; }
#nullable restore
#else
        public global::Soenneker.Make.OpenApiClient.Models.GetImtAppsMeta200ResponseAppsItemComingSoon ComingSoon { get; set; }
#endif
        /// <summary>true if the app is installed from an invite link</summary>
        public bool? Foreign { get; set; }
        /// <summary>true when a (verified) app has been set to &quot;hidden&quot; in the zone (cannot be found in app search) OR when the app is a custom app developed by the requesters organisation and has not been shared with an invite link yet.</summary>
        public bool? IsPrivate { get; set; }
        /// <summary>string of keywords for the app, separated by &quot;, &quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Keywords { get; set; }
#nullable restore
#else
        public string Keywords { get; set; }
#endif
        /// <summary>app label (title)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>app name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>level of premium [0-10], custom apps level defaults to 0</summary>
        public int? PremiumTier { get; set; }
        /// <summary>hex code of color theme for app</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Theme { get; set; }
#nullable restore
#else
        public string Theme { get; set; }
#endif
        /// <summary>app major version [number]</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Models.GetImtAppsMeta200ResponseAppsItem"/> and sets the default values.
        /// </summary>
        public GetImtAppsMeta200ResponseAppsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetImtAppsMeta200ResponseAppsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Make.OpenApiClient.Models.GetImtAppsMeta200ResponseAppsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Make.OpenApiClient.Models.GetImtAppsMeta200ResponseAppsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "app", n => { App = n.GetBoolValue(); } },
                { "brand", n => { Brand = n.GetObjectValue<global::Soenneker.Make.OpenApiClient.Models.GetImtAppsMeta200ResponseAppsItemBrand>(global::Soenneker.Make.OpenApiClient.Models.GetImtAppsMeta200ResponseAppsItemBrand.CreateFromDiscriminatorValue); } },
                { "categories", n => { Categories = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "coming_soon", n => { ComingSoon = n.GetObjectValue<global::Soenneker.Make.OpenApiClient.Models.GetImtAppsMeta200ResponseAppsItemComingSoon>(global::Soenneker.Make.OpenApiClient.Models.GetImtAppsMeta200ResponseAppsItemComingSoon.CreateFromDiscriminatorValue); } },
                { "foreign", n => { Foreign = n.GetBoolValue(); } },
                { "isPrivate", n => { IsPrivate = n.GetBoolValue(); } },
                { "keywords", n => { Keywords = n.GetStringValue(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "premiumTier", n => { PremiumTier = n.GetIntValue(); } },
                { "theme", n => { Theme = n.GetStringValue(); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("app", App);
            writer.WriteObjectValue<global::Soenneker.Make.OpenApiClient.Models.GetImtAppsMeta200ResponseAppsItemBrand>("brand", Brand);
            writer.WriteCollectionOfPrimitiveValues<string>("categories", Categories);
            writer.WriteObjectValue<global::Soenneker.Make.OpenApiClient.Models.GetImtAppsMeta200ResponseAppsItemComingSoon>("coming_soon", ComingSoon);
            writer.WriteBoolValue("foreign", Foreign);
            writer.WriteBoolValue("isPrivate", IsPrivate);
            writer.WriteStringValue("keywords", Keywords);
            writer.WriteStringValue("label", Label);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("premiumTier", PremiumTier);
            writer.WriteStringValue("theme", Theme);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
