// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetOrganizationsOrganizationIdSubscriptionPaymentMethods200_paymentMethods : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created property</summary>
        public DateTimeOffset? Created { get; set; }
        /// <summary>The customerDefaultExtrasMethod property</summary>
        public bool? CustomerDefaultExtrasMethod { get; set; }
        /// <summary>The customerDefaultMethod property</summary>
        public bool? CustomerDefaultMethod { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The isImmediate property</summary>
        public bool? IsImmediate { get; set; }
        /// <summary>The methodDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Make.OpenApiClient.Models.GetOrganizationsOrganizationIdSubscriptionPaymentMethods200_paymentMethods_methodDetails? MethodDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Make.OpenApiClient.Models.GetOrganizationsOrganizationIdSubscriptionPaymentMethods200_paymentMethods_methodDetails MethodDetails { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The valid property</summary>
        public bool? Valid { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Models.GetOrganizationsOrganizationIdSubscriptionPaymentMethods200_paymentMethods"/> and sets the default values.
        /// </summary>
        public GetOrganizationsOrganizationIdSubscriptionPaymentMethods200_paymentMethods()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetOrganizationsOrganizationIdSubscriptionPaymentMethods200_paymentMethods"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Make.OpenApiClient.Models.GetOrganizationsOrganizationIdSubscriptionPaymentMethods200_paymentMethods CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Make.OpenApiClient.Models.GetOrganizationsOrganizationIdSubscriptionPaymentMethods200_paymentMethods();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created", n => { Created = n.GetDateTimeOffsetValue(); } },
                { "customerDefaultExtrasMethod", n => { CustomerDefaultExtrasMethod = n.GetBoolValue(); } },
                { "customerDefaultMethod", n => { CustomerDefaultMethod = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isImmediate", n => { IsImmediate = n.GetBoolValue(); } },
                { "methodDetails", n => { MethodDetails = n.GetObjectValue<global::Soenneker.Make.OpenApiClient.Models.GetOrganizationsOrganizationIdSubscriptionPaymentMethods200_paymentMethods_methodDetails>(global::Soenneker.Make.OpenApiClient.Models.GetOrganizationsOrganizationIdSubscriptionPaymentMethods200_paymentMethods_methodDetails.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "valid", n => { Valid = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created", Created);
            writer.WriteBoolValue("customerDefaultExtrasMethod", CustomerDefaultExtrasMethod);
            writer.WriteBoolValue("customerDefaultMethod", CustomerDefaultMethod);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isImmediate", IsImmediate);
            writer.WriteObjectValue<global::Soenneker.Make.OpenApiClient.Models.GetOrganizationsOrganizationIdSubscriptionPaymentMethods200_paymentMethods_methodDetails>("methodDetails", MethodDetails);
            writer.WriteStringValue("type", Type);
            writer.WriteBoolValue("valid", Valid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
