// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetOrganizationsOrganizationIdManagedOrganizations200_managedOrganizations : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The countryId property</summary>
        public int? CountryId { get; set; }
        /// <summary>The operationsAllocated property</summary>
        public int? OperationsAllocated { get; set; }
        /// <summary>The organizationId property</summary>
        public int? OrganizationId { get; set; }
        /// <summary>The organizationName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationName { get; set; }
#nullable restore
#else
        public string OrganizationName { get; set; }
#endif
        /// <summary>The timezoneId property</summary>
        public int? TimezoneId { get; set; }
        /// <summary>The zoneDomain property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ZoneDomain { get; set; }
#nullable restore
#else
        public string ZoneDomain { get; set; }
#endif
        /// <summary>The zoneId property</summary>
        public int? ZoneId { get; set; }
        /// <summary>The zoneName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ZoneName { get; set; }
#nullable restore
#else
        public string ZoneName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Models.GetOrganizationsOrganizationIdManagedOrganizations200_managedOrganizations"/> and sets the default values.
        /// </summary>
        public GetOrganizationsOrganizationIdManagedOrganizations200_managedOrganizations()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetOrganizationsOrganizationIdManagedOrganizations200_managedOrganizations"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Make.OpenApiClient.Models.GetOrganizationsOrganizationIdManagedOrganizations200_managedOrganizations CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Make.OpenApiClient.Models.GetOrganizationsOrganizationIdManagedOrganizations200_managedOrganizations();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "countryId", n => { CountryId = n.GetIntValue(); } },
                { "operationsAllocated", n => { OperationsAllocated = n.GetIntValue(); } },
                { "organizationId", n => { OrganizationId = n.GetIntValue(); } },
                { "organizationName", n => { OrganizationName = n.GetStringValue(); } },
                { "timezoneId", n => { TimezoneId = n.GetIntValue(); } },
                { "zoneDomain", n => { ZoneDomain = n.GetStringValue(); } },
                { "zoneId", n => { ZoneId = n.GetIntValue(); } },
                { "zoneName", n => { ZoneName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("countryId", CountryId);
            writer.WriteIntValue("operationsAllocated", OperationsAllocated);
            writer.WriteIntValue("organizationId", OrganizationId);
            writer.WriteStringValue("organizationName", OrganizationName);
            writer.WriteIntValue("timezoneId", TimezoneId);
            writer.WriteStringValue("zoneDomain", ZoneDomain);
            writer.WriteIntValue("zoneId", ZoneId);
            writer.WriteStringValue("zoneName", ZoneName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
