// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    /// <summary>
    /// Metadata linking the scenario to the template it was created from, or `null` when the scenario was not created from a template. Returned only when requested via `cols[]`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetScenarios200ResponseScenariosItemTemplateMetadata : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The instantiableId property</summary>
        public int? InstantiableId { get; set; }
        /// <summary>The isOem property</summary>
        public bool? IsOem { get; set; }
        /// <summary>The metadataId property</summary>
        public int? MetadataId { get; set; }
        /// <summary>The versionId property</summary>
        public int? VersionId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Models.GetScenarios200ResponseScenariosItemTemplateMetadata"/> and sets the default values.
        /// </summary>
        public GetScenarios200ResponseScenariosItemTemplateMetadata()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetScenarios200ResponseScenariosItemTemplateMetadata"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Make.OpenApiClient.Models.GetScenarios200ResponseScenariosItemTemplateMetadata CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Make.OpenApiClient.Models.GetScenarios200ResponseScenariosItemTemplateMetadata();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "instantiableId", n => { InstantiableId = n.GetIntValue(); } },
                { "isOem", n => { IsOem = n.GetBoolValue(); } },
                { "metadataId", n => { MetadataId = n.GetIntValue(); } },
                { "versionId", n => { VersionId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("instantiableId", InstantiableId);
            writer.WriteBoolValue("isOem", IsOem);
            writer.WriteIntValue("metadataId", MetadataId);
            writer.WriteIntValue("versionId", VersionId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
