// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetScenariosAiAgents200_scenarios : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The number of AI agent modules in the scenario.</summary>
        public int? AgentCount { get; set; }
        /// <summary>The date and time when the scenario was created.</summary>
        public DateTimeOffset? Created { get; set; }
        /// <summary>The user who created the scenario.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Make.OpenApiClient.Models.GetScenariosAiAgents200_scenarios_createdByUser? CreatedByUser { get; set; }
#nullable restore
#else
        public global::Soenneker.Make.OpenApiClient.Models.GetScenariosAiAgents200_scenarios_createdByUser CreatedByUser { get; set; }
#endif
        /// <summary>The description of the scenario.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The unique ID of the scenario.</summary>
        public int? Id { get; set; }
        /// <summary>Whether the scenario is currently active.</summary>
        public bool? IsActive { get; set; }
        /// <summary>The date and time when the scenario was last edited.</summary>
        public DateTimeOffset? LastEdit { get; set; }
        /// <summary>The name of the scenario.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The scheduling configuration of the scenario.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Make.OpenApiClient.Models.GetScenariosAiAgents200_scenarios_scheduling? Scheduling { get; set; }
#nullable restore
#else
        public global::Soenneker.Make.OpenApiClient.Models.GetScenariosAiAgents200_scenarios_scheduling Scheduling { get; set; }
#endif
        /// <summary>The unique ID of the team.</summary>
        public int? TeamId { get; set; }
        /// <summary>The list of app packages used in the scenario.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? UsedPackages { get; set; }
#nullable restore
#else
        public List<string> UsedPackages { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Models.GetScenariosAiAgents200_scenarios"/> and sets the default values.
        /// </summary>
        public GetScenariosAiAgents200_scenarios()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetScenariosAiAgents200_scenarios"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Make.OpenApiClient.Models.GetScenariosAiAgents200_scenarios CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Make.OpenApiClient.Models.GetScenariosAiAgents200_scenarios();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agentCount", n => { AgentCount = n.GetIntValue(); } },
                { "created", n => { Created = n.GetDateTimeOffsetValue(); } },
                { "createdByUser", n => { CreatedByUser = n.GetObjectValue<global::Soenneker.Make.OpenApiClient.Models.GetScenariosAiAgents200_scenarios_createdByUser>(global::Soenneker.Make.OpenApiClient.Models.GetScenariosAiAgents200_scenarios_createdByUser.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "lastEdit", n => { LastEdit = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "scheduling", n => { Scheduling = n.GetObjectValue<global::Soenneker.Make.OpenApiClient.Models.GetScenariosAiAgents200_scenarios_scheduling>(global::Soenneker.Make.OpenApiClient.Models.GetScenariosAiAgents200_scenarios_scheduling.CreateFromDiscriminatorValue); } },
                { "teamId", n => { TeamId = n.GetIntValue(); } },
                { "usedPackages", n => { UsedPackages = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("agentCount", AgentCount);
            writer.WriteDateTimeOffsetValue("created", Created);
            writer.WriteObjectValue<global::Soenneker.Make.OpenApiClient.Models.GetScenariosAiAgents200_scenarios_createdByUser>("createdByUser", CreatedByUser);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteDateTimeOffsetValue("lastEdit", LastEdit);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Make.OpenApiClient.Models.GetScenariosAiAgents200_scenarios_scheduling>("scheduling", Scheduling);
            writer.WriteIntValue("teamId", TeamId);
            writer.WriteCollectionOfPrimitiveValues<string>("usedPackages", UsedPackages);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
