// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetScenariosLogs200ResponseScenarioLogsItemEventType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "EXECUTION_END")]
        #pragma warning disable CS1591
        ExecutionEnd,
        #pragma warning restore CS1591
    }
}
