// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetScenarioSharesList200ResponseScenariosSharedItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Timestamp when the shared scenario was created</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Short description of the shared scenario</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DescriptionShort { get; set; }
#nullable restore
#else
        public string DescriptionShort { get; set; }
#endif
        /// <summary>Unique identifier of the shared scenario</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>ID of the original scenario</summary>
        public int? ScenarioId { get; set; }
        /// <summary>Name of the original scenario</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScenarioName { get; set; }
#nullable restore
#else
        public string ScenarioName { get; set; }
#endif
        /// <summary>List of packages/modules used in the scenario</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ScenarioUsedPackages { get; set; }
#nullable restore
#else
        public List<string> ScenarioUsedPackages { get; set; }
#endif
        /// <summary>Public URL for accessing the shared scenario</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShareUrl { get; set; }
#nullable restore
#else
        public string ShareUrl { get; set; }
#endif
        /// <summary>Title of the shared scenario</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Timestamp when the shared scenario was last updated</summary>
        public DateTimeOffset? Updated { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Models.GetScenarioSharesList200ResponseScenariosSharedItem"/> and sets the default values.
        /// </summary>
        public GetScenarioSharesList200ResponseScenariosSharedItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetScenarioSharesList200ResponseScenariosSharedItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Make.OpenApiClient.Models.GetScenarioSharesList200ResponseScenariosSharedItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Make.OpenApiClient.Models.GetScenarioSharesList200ResponseScenariosSharedItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "descriptionShort", n => { DescriptionShort = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "scenarioId", n => { ScenarioId = n.GetIntValue(); } },
                { "scenarioName", n => { ScenarioName = n.GetStringValue(); } },
                { "scenarioUsedPackages", n => { ScenarioUsedPackages = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "shareUrl", n => { ShareUrl = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "updated", n => { Updated = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("descriptionShort", DescriptionShort);
            writer.WriteStringValue("id", Id);
            writer.WriteIntValue("scenarioId", ScenarioId);
            writer.WriteStringValue("scenarioName", ScenarioName);
            writer.WriteCollectionOfPrimitiveValues<string>("scenarioUsedPackages", ScenarioUsedPackages);
            writer.WriteStringValue("shareUrl", ShareUrl);
            writer.WriteStringValue("title", Title);
            writer.WriteDateTimeOffsetValue("updated", Updated);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
