// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetUsersMe200ResponseAuthUser : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The avatar property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Avatar { get; set; }
#nullable restore
#else
        public string Avatar { get; set; }
#endif
        /// <summary>The countryId property</summary>
        public int? CountryId { get; set; }
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The features property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Make.OpenApiClient.Models.GetUsersMe200ResponseAuthUserFeatures? Features { get; set; }
#nullable restore
#else
        public global::Soenneker.Make.OpenApiClient.Models.GetUsersMe200ResponseAuthUserFeatures Features { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The language property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Language { get; set; }
#nullable restore
#else
        public string Language { get; set; }
#endif
        /// <summary>The lastLogin property</summary>
        public DateTimeOffset? LastLogin { get; set; }
        /// <summary>The localeId property</summary>
        public int? LocaleId { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The user&apos;s personal private space in the organization. Only returned when explicitly requested via cols[]=privateSpace with organizationId on a public instance.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Make.OpenApiClient.Models.GetUsersMe200ResponseAuthUserPrivateSpace? PrivateSpace { get; set; }
#nullable restore
#else
        public global::Soenneker.Make.OpenApiClient.Models.GetUsersMe200ResponseAuthUserPrivateSpace PrivateSpace { get; set; }
#endif
        /// <summary>Whether the user is eligible for contact support. False if all user&apos;s organizations are on Free plan and account is older than 90 days.</summary>
        public bool? SupportEligible { get; set; }
        /// <summary>&quot;Two-factor authentication status:- 0: No TFA set- 1: TFA active (authenticator app)- 2: External authentication (Social SSO)It is only supported on Make&apos;s public cloud instances.&quot;</summary>
        public int? TfaStatus { get; set; }
        /// <summary>The timezoneId property</summary>
        public int? TimezoneId { get; set; }
        /// <summary>IDs of teams the user belongs to within the organization. Only returned when explicitly requested via cols[]=userTeamIds and organizationId is provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? UserTeamIds { get; set; }
#nullable restore
#else
        public List<int?> UserTeamIds { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Models.GetUsersMe200ResponseAuthUser"/> and sets the default values.
        /// </summary>
        public GetUsersMe200ResponseAuthUser()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetUsersMe200ResponseAuthUser"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Make.OpenApiClient.Models.GetUsersMe200ResponseAuthUser CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Make.OpenApiClient.Models.GetUsersMe200ResponseAuthUser();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "avatar", n => { Avatar = n.GetStringValue(); } },
                { "countryId", n => { CountryId = n.GetIntValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "features", n => { Features = n.GetObjectValue<global::Soenneker.Make.OpenApiClient.Models.GetUsersMe200ResponseAuthUserFeatures>(global::Soenneker.Make.OpenApiClient.Models.GetUsersMe200ResponseAuthUserFeatures.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "language", n => { Language = n.GetStringValue(); } },
                { "lastLogin", n => { LastLogin = n.GetDateTimeOffsetValue(); } },
                { "localeId", n => { LocaleId = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "privateSpace", n => { PrivateSpace = n.GetObjectValue<global::Soenneker.Make.OpenApiClient.Models.GetUsersMe200ResponseAuthUserPrivateSpace>(global::Soenneker.Make.OpenApiClient.Models.GetUsersMe200ResponseAuthUserPrivateSpace.CreateFromDiscriminatorValue); } },
                { "supportEligible", n => { SupportEligible = n.GetBoolValue(); } },
                { "tfaStatus", n => { TfaStatus = n.GetIntValue(); } },
                { "timezoneId", n => { TimezoneId = n.GetIntValue(); } },
                { "userTeamIds", n => { UserTeamIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("avatar", Avatar);
            writer.WriteIntValue("countryId", CountryId);
            writer.WriteStringValue("email", Email);
            writer.WriteObjectValue<global::Soenneker.Make.OpenApiClient.Models.GetUsersMe200ResponseAuthUserFeatures>("features", Features);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("language", Language);
            writer.WriteDateTimeOffsetValue("lastLogin", LastLogin);
            writer.WriteIntValue("localeId", LocaleId);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Make.OpenApiClient.Models.GetUsersMe200ResponseAuthUserPrivateSpace>("privateSpace", PrivateSpace);
            writer.WriteBoolValue("supportEligible", SupportEligible);
            writer.WriteIntValue("tfaStatus", TfaStatus);
            writer.WriteIntValue("timezoneId", TimezoneId);
            writer.WriteCollectionOfPrimitiveValues<int?>("userTeamIds", UserTeamIds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
