// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PatchDataStructuresByDataStructureIdRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The name of the data structure. The maximum length of the name is 128 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Sets the data structure specification. Note that when you update the data structure specification with the `spec` parameter, you have to provide all structure fields you want to use. Make replaces the old structure specification with the new one.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItem>? Spec { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItem> Spec { get; set; }
#endif
        /// <summary>Set to `true` to enforce strict validation of the data put in the data structure. With the strict validation enabled, the data structure won&apos;t store data that don&apos;t fit into the structure and the storing module will return an error.The default value of this parameter is `false`. With the default setting, the modules using the data structure will process data that don&apos;t conform to the data structure.</summary>
        public bool? Strict { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequest"/> and sets the default values.
        /// </summary>
        public PatchDataStructuresByDataStructureIdRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "name", n => { Name = n.GetStringValue(); } },
                { "spec", n => { Spec = n.GetCollectionOfObjectValues<global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItem>(global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "strict", n => { Strict = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItem>("spec", Spec);
            writer.WriteBoolValue("strict", Strict);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
