// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PatchDataStructuresByDataStructureIdRequestSpecItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The codepage property</summary>
        public global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItemCodepage? Codepage { get; set; }
        /// <summary>The default property</summary>
        public bool? Default { get; set; }
        /// <summary>The label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>The multiline property</summary>
        public bool? Multiline { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The required property</summary>
        public bool? Required { get; set; }
        /// <summary>The sequence property</summary>
        public bool? Sequence { get; set; }
        /// <summary>The spec property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItemSpecItem>? Spec { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItemSpecItem> Spec { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItemType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItem"/> and sets the default values.
        /// </summary>
        public PatchDataStructuresByDataStructureIdRequestSpecItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "codepage", n => { Codepage = n.GetEnumValue<global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItemCodepage>(); } },
                { "default", n => { Default = n.GetBoolValue(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "multiline", n => { Multiline = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "required", n => { Required = n.GetBoolValue(); } },
                { "sequence", n => { Sequence = n.GetBoolValue(); } },
                { "spec", n => { Spec = n.GetCollectionOfObjectValues<global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItemSpecItem>(global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItemSpecItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItemType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItemCodepage>("codepage", Codepage);
            writer.WriteBoolValue("default", Default);
            writer.WriteStringValue("label", Label);
            writer.WriteBoolValue("multiline", Multiline);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("required", Required);
            writer.WriteBoolValue("sequence", Sequence);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItemSpecItem>("spec", Spec);
            writer.WriteEnumValue<global::Soenneker.Make.OpenApiClient.Models.PatchDataStructuresByDataStructureIdRequestSpecItemType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
