// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch1"/>, <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch2"/>, <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch3"/>, <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch5"/>, <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueMember1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValue : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch1? PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch1 PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch2? PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch2 PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch3? PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch3 PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch5? PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch5 PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueMember1? PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueMember1 PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueMember1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValue();
            if("PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch1 = new global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch1();
            }
            else if("PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch2 = new global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch2();
            }
            else if("PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch3 = new global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch3();
            }
            else if("PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch5".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch5 = new global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch5();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch1 != null)
            {
                return PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch1.GetFieldDeserializers();
            }
            else if(PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch2 != null)
            {
                return PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch2.GetFieldDeserializers();
            }
            else if(PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch3 != null)
            {
                return PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch3.GetFieldDeserializers();
            }
            else if(PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch5 != null)
            {
                return PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch5.GetFieldDeserializers();
            }
            else if(PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueMember1 != null)
            {
                return PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueMember1.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch1>(null, PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch1);
            }
            else if(PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch2>(null, PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch2);
            }
            else if(PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch3>(null, PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch3);
            }
            else if(PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch5 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch5>(null, PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueBranch5);
            }
            else if(PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueMember1>(null, PatchOrganizationsByOrganizationIdVariablesByVariableNameRequestValueMember1);
            }
        }
    }
}
#pragma warning restore CS0618
