// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    /// <summary>
    /// Request body for modifying an existing agent.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PatchAiAgentsV1AgentsAgentId : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The defaultModel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultModel { get; set; }
#nullable restore
#else
        public string DefaultModel { get; set; }
#endif
        /// <summary>The historyConfig property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_historyConfig? HistoryConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_historyConfig HistoryConfig { get; set; }
#endif
        /// <summary>The invocationConfig property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_invocationConfig? InvocationConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_invocationConfig InvocationConfig { get; set; }
#endif
        /// <summary>The llmConfig property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_llmConfig? LlmConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_llmConfig LlmConfig { get; set; }
#endif
        /// <summary>The mcpConfigs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_mcpConfigs>? McpConfigs { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_mcpConfigs> McpConfigs { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The outputParserFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId.PatchAiAgentsV1AgentsAgentId_outputParserFormat? OutputParserFormat { get; set; }
#nullable restore
#else
        public global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId.PatchAiAgentsV1AgentsAgentId_outputParserFormat OutputParserFormat { get; set; }
#endif
        /// <summary>The scenarios property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_scenarios>? Scenarios { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_scenarios> Scenarios { get; set; }
#endif
        /// <summary>The systemPrompt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SystemPrompt { get; set; }
#nullable restore
#else
        public string SystemPrompt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId"/> and sets the default values.
        /// </summary>
        public PatchAiAgentsV1AgentsAgentId()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "defaultModel", n => { DefaultModel = n.GetStringValue(); } },
                { "historyConfig", n => { HistoryConfig = n.GetObjectValue<global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_historyConfig>(global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_historyConfig.CreateFromDiscriminatorValue); } },
                { "invocationConfig", n => { InvocationConfig = n.GetObjectValue<global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_invocationConfig>(global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_invocationConfig.CreateFromDiscriminatorValue); } },
                { "llmConfig", n => { LlmConfig = n.GetObjectValue<global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_llmConfig>(global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_llmConfig.CreateFromDiscriminatorValue); } },
                { "mcpConfigs", n => { McpConfigs = n.GetCollectionOfObjectValues<global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_mcpConfigs>(global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_mcpConfigs.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "outputParserFormat", n => { OutputParserFormat = n.GetObjectValue<global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId.PatchAiAgentsV1AgentsAgentId_outputParserFormat>(global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId.PatchAiAgentsV1AgentsAgentId_outputParserFormat.CreateFromDiscriminatorValue); } },
                { "scenarios", n => { Scenarios = n.GetCollectionOfObjectValues<global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_scenarios>(global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_scenarios.CreateFromDiscriminatorValue)?.AsList(); } },
                { "systemPrompt", n => { SystemPrompt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("defaultModel", DefaultModel);
            writer.WriteObjectValue<global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_historyConfig>("historyConfig", HistoryConfig);
            writer.WriteObjectValue<global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_invocationConfig>("invocationConfig", InvocationConfig);
            writer.WriteObjectValue<global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_llmConfig>("llmConfig", LlmConfig);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_mcpConfigs>("mcpConfigs", McpConfigs);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId.PatchAiAgentsV1AgentsAgentId_outputParserFormat>("outputParserFormat", OutputParserFormat);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_scenarios>("scenarios", Scenarios);
            writer.WriteStringValue("systemPrompt", SystemPrompt);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_outputParserFormatMember1"/>, <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_outputParserFormatMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PatchAiAgentsV1AgentsAgentId_outputParserFormat : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_outputParserFormatMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_outputParserFormatMember1? PatchAiAgentsV1AgentsAgentIdOutputParserFormatMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_outputParserFormatMember1 PatchAiAgentsV1AgentsAgentIdOutputParserFormatMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_outputParserFormatMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_outputParserFormatMember2? PatchAiAgentsV1AgentsAgentIdOutputParserFormatMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_outputParserFormatMember2 PatchAiAgentsV1AgentsAgentIdOutputParserFormatMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId.PatchAiAgentsV1AgentsAgentId_outputParserFormat"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId.PatchAiAgentsV1AgentsAgentId_outputParserFormat CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId.PatchAiAgentsV1AgentsAgentId_outputParserFormat();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PatchAiAgentsV1AgentsAgentIdOutputParserFormatMember1 = new global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_outputParserFormatMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PatchAiAgentsV1AgentsAgentIdOutputParserFormatMember2 = new global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_outputParserFormatMember2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(PatchAiAgentsV1AgentsAgentIdOutputParserFormatMember1 != null)
                {
                    return PatchAiAgentsV1AgentsAgentIdOutputParserFormatMember1.GetFieldDeserializers();
                }
                else if(PatchAiAgentsV1AgentsAgentIdOutputParserFormatMember2 != null)
                {
                    return PatchAiAgentsV1AgentsAgentIdOutputParserFormatMember2.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(PatchAiAgentsV1AgentsAgentIdOutputParserFormatMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_outputParserFormatMember1>(null, PatchAiAgentsV1AgentsAgentIdOutputParserFormatMember1);
                }
                else if(PatchAiAgentsV1AgentsAgentIdOutputParserFormatMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Make.OpenApiClient.Models.PatchAiAgentsV1AgentsAgentId_outputParserFormatMember2>(null, PatchAiAgentsV1AgentsAgentIdOutputParserFormatMember2);
                }
            }
        }
    }
}
#pragma warning restore CS0618
