// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostTemplates200_template : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The approved property</summary>
        public DateTimeOffset? Approved { get; set; }
        /// <summary>The approvedId property</summary>
        public int? ApprovedId { get; set; }
        /// <summary>The approvedName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApprovedName { get; set; }
#nullable restore
#else
        public string ApprovedName { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The organizationId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The public property</summary>
        public bool? Public { get; set; }
        /// <summary>The publicUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicUrl { get; set; }
#nullable restore
#else
        public string PublicUrl { get; set; }
#endif
        /// <summary>The published property</summary>
        public DateTimeOffset? Published { get; set; }
        /// <summary>The publishedId property</summary>
        public int? PublishedId { get; set; }
        /// <summary>The publishedName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublishedName { get; set; }
#nullable restore
#else
        public string PublishedName { get; set; }
#endif
        /// <summary>The requestedApproval property</summary>
        public bool? RequestedApproval { get; set; }
        /// <summary>The teamId property</summary>
        public int? TeamId { get; set; }
        /// <summary>The teamName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamName { get; set; }
#nullable restore
#else
        public string TeamName { get; set; }
#endif
        /// <summary>The usedApps property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? UsedApps { get; set; }
#nullable restore
#else
        public List<string> UsedApps { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Models.PostTemplates200_template"/> and sets the default values.
        /// </summary>
        public PostTemplates200_template()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.PostTemplates200_template"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Make.OpenApiClient.Models.PostTemplates200_template CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Make.OpenApiClient.Models.PostTemplates200_template();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "approved", n => { Approved = n.GetDateTimeOffsetValue(); } },
                { "approvedId", n => { ApprovedId = n.GetIntValue(); } },
                { "approvedName", n => { ApprovedName = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "organizationId", n => { OrganizationId = n.GetStringValue(); } },
                { "public", n => { Public = n.GetBoolValue(); } },
                { "publicUrl", n => { PublicUrl = n.GetStringValue(); } },
                { "published", n => { Published = n.GetDateTimeOffsetValue(); } },
                { "publishedId", n => { PublishedId = n.GetIntValue(); } },
                { "publishedName", n => { PublishedName = n.GetStringValue(); } },
                { "requestedApproval", n => { RequestedApproval = n.GetBoolValue(); } },
                { "teamId", n => { TeamId = n.GetIntValue(); } },
                { "teamName", n => { TeamName = n.GetStringValue(); } },
                { "usedApps", n => { UsedApps = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("approved", Approved);
            writer.WriteIntValue("approvedId", ApprovedId);
            writer.WriteStringValue("approvedName", ApprovedName);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("organizationId", OrganizationId);
            writer.WriteBoolValue("public", Public);
            writer.WriteStringValue("publicUrl", PublicUrl);
            writer.WriteDateTimeOffsetValue("published", Published);
            writer.WriteIntValue("publishedId", PublishedId);
            writer.WriteStringValue("publishedName", PublishedName);
            writer.WriteBoolValue("requestedApproval", RequestedApproval);
            writer.WriteIntValue("teamId", TeamId);
            writer.WriteStringValue("teamName", TeamName);
            writer.WriteCollectionOfPrimitiveValues<string>("usedApps", UsedApps);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
