// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    /// <summary>Entity kind the file belongs to.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostSdkAppsBySdkAppNameBySdkAppVersionGithubBySdkGithubBindingIdPull200ResponseChangesItemGroup
    {
        [EnumMember(Value = "app")]
        #pragma warning disable CS1591
        App,
        #pragma warning restore CS1591
        [EnumMember(Value = "module")]
        #pragma warning disable CS1591
        Module,
        #pragma warning restore CS1591
        [EnumMember(Value = "rpc")]
        #pragma warning disable CS1591
        Rpc,
        #pragma warning restore CS1591
        [EnumMember(Value = "function")]
        #pragma warning disable CS1591
        Function,
        #pragma warning restore CS1591
        [EnumMember(Value = "hook")]
        #pragma warning disable CS1591
        Hook,
        #pragma warning restore CS1591
        [EnumMember(Value = "account")]
        #pragma warning disable CS1591
        Account,
        #pragma warning restore CS1591
    }
}
