// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PostAdminScenariosReactivate200ResponseResultsItemStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "reactivated")]
        #pragma warning disable CS1591
        Reactivated,
        #pragma warning restore CS1591
        [EnumMember(Value = "would_reactivate")]
        #pragma warning disable CS1591
        WouldReactivate,
        #pragma warning restore CS1591
        [EnumMember(Value = "already_active")]
        #pragma warning disable CS1591
        AlreadyActive,
        #pragma warning restore CS1591
        [EnumMember(Value = "deleted")]
        #pragma warning disable CS1591
        Deleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "executing")]
        #pragma warning disable CS1591
        Executing,
        #pragma warning restore CS1591
        [EnumMember(Value = "locked")]
        #pragma warning disable CS1591
        Locked,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_found")]
        #pragma warning disable CS1591
        NotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
    }
}
