// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostAdminOrganizationsOrganizationIdAssignUniversalDiscount : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Whether to activate the discount immediately</summary>
        public bool? ActivateImmediately { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Custom banner text for the discount (overrides the type default)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BannerText { get; set; }
#nullable restore
#else
        public string BannerText { get; set; }
#endif
        /// <summary>The type of discount to assign</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DiscountType { get; set; }
#nullable restore
#else
        public string DiscountType { get; set; }
#endif
        /// <summary>The duration of the discount in months</summary>
        public int? DurationInMonths { get; set; }
        /// <summary>The percentage off for the discount (1-100)</summary>
        public double? PercentOff { get; set; }
        /// <summary>The date until which the discount can be redeemed</summary>
        public Date? RedeemUntil { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Models.PostAdminOrganizationsOrganizationIdAssignUniversalDiscount"/> and sets the default values.
        /// </summary>
        public PostAdminOrganizationsOrganizationIdAssignUniversalDiscount()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.PostAdminOrganizationsOrganizationIdAssignUniversalDiscount"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Make.OpenApiClient.Models.PostAdminOrganizationsOrganizationIdAssignUniversalDiscount CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Make.OpenApiClient.Models.PostAdminOrganizationsOrganizationIdAssignUniversalDiscount();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activateImmediately", n => { ActivateImmediately = n.GetBoolValue(); } },
                { "bannerText", n => { BannerText = n.GetStringValue(); } },
                { "discountType", n => { DiscountType = n.GetStringValue(); } },
                { "durationInMonths", n => { DurationInMonths = n.GetIntValue(); } },
                { "percentOff", n => { PercentOff = n.GetDoubleValue(); } },
                { "redeemUntil", n => { RedeemUntil = n.GetDateValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("activateImmediately", ActivateImmediately);
            writer.WriteStringValue("bannerText", BannerText);
            writer.WriteStringValue("discountType", DiscountType);
            writer.WriteIntValue("durationInMonths", DurationInMonths);
            writer.WriteDoubleValue("percentOff", PercentOff);
            writer.WriteDateValue("redeemUntil", RedeemUntil);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
