// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PostAiAgentsV1AgentsByAgentIdRun200ResponseExecutionStepsItemToolResponseStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ok")]
        #pragma warning disable CS1591
        Ok,
        #pragma warning restore CS1591
        [EnumMember(Value = "fail")]
        #pragma warning disable CS1591
        Fail,
        #pragma warning restore CS1591
    }
}
