// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Make.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PutAdminSdkAppReviewCategoriesRequestRequestBodyItem : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Human-readable label of the category.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Category { get; set; }
#nullable restore
#else
        public string Category { get; set; }
#endif
        /// <summary>Stable identifier of the category. Optional — derived from `category` when omitted. Must already be in canonical form.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>The category&apos;s subcategories in display order. Omit or pass an empty array for a category with none.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Make.OpenApiClient.Models.PutAdminSdkAppReviewCategoriesRequestItemSubcategoriesItem>? Subcategories { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Make.OpenApiClient.Models.PutAdminSdkAppReviewCategoriesRequestItemSubcategoriesItem> Subcategories { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.PutAdminSdkAppReviewCategoriesRequestRequestBodyItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Make.OpenApiClient.Models.PutAdminSdkAppReviewCategoriesRequestRequestBodyItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Make.OpenApiClient.Models.PutAdminSdkAppReviewCategoriesRequestRequestBodyItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "category", n => { Category = n.GetStringValue(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "subcategories", n => { Subcategories = n.GetCollectionOfObjectValues<global::Soenneker.Make.OpenApiClient.Models.PutAdminSdkAppReviewCategoriesRequestItemSubcategoriesItem>(global::Soenneker.Make.OpenApiClient.Models.PutAdminSdkAppReviewCategoriesRequestItemSubcategoriesItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("category", Category);
            writer.WriteStringValue("slug", Slug);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Make.OpenApiClient.Models.PutAdminSdkAppReviewCategoriesRequestItemSubcategoriesItem>("subcategories", Subcategories);
        }
    }
}
#pragma warning restore CS0618
