// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Make.OpenApiClient.CredentialRequests.Apps.Item.Item.ModulesWithCredentials;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Make.OpenApiClient.CredentialRequests.Apps.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \credential-requests\apps\{name}\{version}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithVersionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The modulesWithCredentials property</summary>
        public global::Soenneker.Make.OpenApiClient.CredentialRequests.Apps.Item.Item.ModulesWithCredentials.ModulesWithCredentialsRequestBuilder ModulesWithCredentials
        {
            get => new global::Soenneker.Make.OpenApiClient.CredentialRequests.Apps.Item.Item.ModulesWithCredentials.ModulesWithCredentialsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.CredentialRequests.Apps.Item.Item.WithVersionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithVersionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/credential-requests/apps/{name}/{version}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.CredentialRequests.Apps.Item.Item.WithVersionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithVersionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/credential-requests/apps/{name}/{version}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
