// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Make.OpenApiClient.Cashier.Products
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "PLAN")]
        #pragma warning disable CS1591
        PLAN,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXTRA")]
        #pragma warning disable CS1591
        EXTRA,
        #pragma warning restore CS1591
    }
}
