// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Make.OpenApiClient.Internal.Hooks.Item;
using Soenneker.Make.OpenApiClient.Internal.Hooks.Register;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Make.OpenApiClient.Internal.Hooks
{
    /// <summary>
    /// Builds and executes requests for operations under \internal\hooks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HooksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The register property</summary>
        public global::Soenneker.Make.OpenApiClient.Internal.Hooks.Register.RegisterRequestBuilder Register
        {
            get => new global::Soenneker.Make.OpenApiClient.Internal.Hooks.Register.RegisterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Make.OpenApiClient.internal.hooks.item collection</summary>
        /// <param name="position">The id of the hook to update.</param>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Internal.Hooks.Item.WithHookItemRequestBuilder"/></returns>
        public global::Soenneker.Make.OpenApiClient.Internal.Hooks.Item.WithHookItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("hookId", position);
                return new global::Soenneker.Make.OpenApiClient.Internal.Hooks.Item.WithHookItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Internal.Hooks.HooksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HooksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/internal/hooks", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Internal.Hooks.HooksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HooksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/internal/hooks", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
