// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Make.OpenApiClient.AuditLogs.V2.Organization.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Make.OpenApiClient.AuditLogs.V2.Organization
{
    /// <summary>
    /// Builds and executes requests for operations under \audit-logs\v2\organization
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrganizationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Make.OpenApiClient.auditLogs.v2.organization.item collection</summary>
        /// <param name="position">The positive ID of the organization.</param>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.AuditLogs.V2.Organization.Item.WithOrganizationItemRequestBuilder"/></returns>
        public global::Soenneker.Make.OpenApiClient.AuditLogs.V2.Organization.Item.WithOrganizationItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("organizationId", position);
                return new global::Soenneker.Make.OpenApiClient.AuditLogs.V2.Organization.Item.WithOrganizationItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.AuditLogs.V2.Organization.OrganizationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrganizationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/audit-logs/v2/organization", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.AuditLogs.V2.Organization.OrganizationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrganizationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/audit-logs/v2/organization", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
