// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Make.OpenApiClient.Models;
using Soenneker.Make.OpenApiClient.Organizations.Item.Apps;
using Soenneker.Make.OpenApiClient.Organizations.Item.CheckTeamPermission;
using Soenneker.Make.OpenApiClient.Organizations.Item.Domains;
using Soenneker.Make.OpenApiClient.Organizations.Item.FeatureControls;
using Soenneker.Make.OpenApiClient.Organizations.Item.Invite;
using Soenneker.Make.OpenApiClient.Organizations.Item.ManagedOrganizations;
using Soenneker.Make.OpenApiClient.Organizations.Item.ManagedOrganizationsConsumption;
using Soenneker.Make.OpenApiClient.Organizations.Item.Payments;
using Soenneker.Make.OpenApiClient.Organizations.Item.Scenarios;
using Soenneker.Make.OpenApiClient.Organizations.Item.SsoCertificates;
using Soenneker.Make.OpenApiClient.Organizations.Item.Subscription;
using Soenneker.Make.OpenApiClient.Organizations.Item.SubscriptionFree;
using Soenneker.Make.OpenApiClient.Organizations.Item.TestClock;
using Soenneker.Make.OpenApiClient.Organizations.Item.TestPauseUnpause;
using Soenneker.Make.OpenApiClient.Organizations.Item.TfaEnforcement;
using Soenneker.Make.OpenApiClient.Organizations.Item.UniversalDiscount;
using Soenneker.Make.OpenApiClient.Organizations.Item.Usage;
using Soenneker.Make.OpenApiClient.Organizations.Item.UserOrganizationRoles;
using Soenneker.Make.OpenApiClient.Organizations.Item.Variables;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Make.OpenApiClient.Organizations.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \organizations\{organizationId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithOrganizationItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The apps property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.Apps.AppsRequestBuilder Apps
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.Apps.AppsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The checkTeamPermission property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.CheckTeamPermission.CheckTeamPermissionRequestBuilder CheckTeamPermission
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.CheckTeamPermission.CheckTeamPermissionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The domains property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.Domains.DomainsRequestBuilder Domains
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.Domains.DomainsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The featureControls property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.FeatureControls.FeatureControlsRequestBuilder FeatureControls
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.FeatureControls.FeatureControlsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The invite property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.Invite.InviteRequestBuilder Invite
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.Invite.InviteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The managedOrganizations property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.ManagedOrganizations.ManagedOrganizationsRequestBuilder ManagedOrganizations
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.ManagedOrganizations.ManagedOrganizationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The managedOrganizationsConsumption property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.ManagedOrganizationsConsumption.ManagedOrganizationsConsumptionRequestBuilder ManagedOrganizationsConsumption
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.ManagedOrganizationsConsumption.ManagedOrganizationsConsumptionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The payments property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.Payments.PaymentsRequestBuilder Payments
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.Payments.PaymentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The scenarios property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.Scenarios.ScenariosRequestBuilder Scenarios
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.Scenarios.ScenariosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ssoCertificates property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.SsoCertificates.SsoCertificatesRequestBuilder SsoCertificates
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.SsoCertificates.SsoCertificatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subscription property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.Subscription.SubscriptionRequestBuilder Subscription
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.Subscription.SubscriptionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subscriptionFree property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.SubscriptionFree.SubscriptionFreeRequestBuilder SubscriptionFree
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.SubscriptionFree.SubscriptionFreeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The testClock property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.TestClock.TestClockRequestBuilder TestClock
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.TestClock.TestClockRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The testPauseUnpause property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.TestPauseUnpause.TestPauseUnpauseRequestBuilder TestPauseUnpause
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.TestPauseUnpause.TestPauseUnpauseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tfaEnforcement property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.TfaEnforcement.TfaEnforcementRequestBuilder TfaEnforcement
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.TfaEnforcement.TfaEnforcementRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The universalDiscount property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.UniversalDiscount.UniversalDiscountRequestBuilder UniversalDiscount
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.UniversalDiscount.UniversalDiscountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The usage property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.Usage.UsageRequestBuilder Usage
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.Usage.UsageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userOrganizationRoles property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.UserOrganizationRoles.UserOrganizationRolesRequestBuilder UserOrganizationRoles
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.UserOrganizationRoles.UserOrganizationRolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The variables property</summary>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.Variables.VariablesRequestBuilder Variables
        {
            get => new global::Soenneker.Make.OpenApiClient.Organizations.Item.Variables.VariablesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Organizations.Item.WithOrganizationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOrganizationItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organizations/{organizationId}{?confirmed*,wait*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Organizations.Item.WithOrganizationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOrganizationItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organizations/{organizationId}{?confirmed*,wait*}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;Deletes the organization with the specified `organizationId`. Make also deletes all the teams in the organization.  You can only delete organizations that are associated with your current Make zone. Your current Make zone is specified in the API call URL. Currently, it is either:  - `eu1.make.com`  - `us1.make.com`&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.DeleteOrganizationsByOrganizationId200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.DeleteOrganizationsByOrganizationId200Response?> DeleteAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Organizations.Item.WithOrganizationItemRequestBuilder.WithOrganizationItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.DeleteOrganizationsByOrganizationId200Response> DeleteAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Organizations.Item.WithOrganizationItemRequestBuilder.WithOrganizationItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.DeleteOrganizationsByOrganizationId200Response>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.DeleteOrganizationsByOrganizationId200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves detail information of the organization with the specified `organizationId`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetOrganizationsByOrganizationId200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetOrganizationsByOrganizationId200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Organizations.Item.WithOrganizationItemRequestBuilder.WithOrganizationItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetOrganizationsByOrganizationId200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Organizations.Item.WithOrganizationItemRequestBuilder.WithOrganizationItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.GetOrganizationsByOrganizationId200Response>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.GetOrganizationsByOrganizationId200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates the organization data with the values in the request body. If you don&apos;t use a parameter in the request body, Make won&apos;t change its value. You can update organization name, timezone, and country with the `name`, `timezoneId`, and `countryId` parameters.Check the available values for the `timezoneId` and `countryId` parameters with the API calls `GET /enums/timezones` and `GET /enums/countries`.The request response returns all organization data.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationId200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationId200Response?> PatchAsync(global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationId200Response> PatchAsync(global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationId200Response>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationId200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Deletes the organization with the specified `organizationId`. Make also deletes all the teams in the organization.  You can only delete organizations that are associated with your current Make zone. Your current Make zone is specified in the API call URL. Currently, it is either:  - `eu1.make.com`  - `us1.make.com`&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Organizations.Item.WithOrganizationItemRequestBuilder.WithOrganizationItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Organizations.Item.WithOrganizationItemRequestBuilder.WithOrganizationItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Retrieves detail information of the organization with the specified `organizationId`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Organizations.Item.WithOrganizationItemRequestBuilder.WithOrganizationItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Organizations.Item.WithOrganizationItemRequestBuilder.WithOrganizationItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates the organization data with the values in the request body. If you don&apos;t use a parameter in the request body, Make won&apos;t change its value. You can update organization name, timezone, and country with the `name`, `timezoneId`, and `countryId` parameters.Check the available values for the `timezoneId` and `countryId` parameters with the API calls `GET /enums/timezones` and `GET /enums/countries`.The request response returns all organization data.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Make.OpenApiClient.Models.PatchOrganizationsByOrganizationIdRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Organizations.Item.WithOrganizationItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Make.OpenApiClient.Organizations.Item.WithOrganizationItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Make.OpenApiClient.Organizations.Item.WithOrganizationItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &quot;Deletes the organization with the specified `organizationId`. Make also deletes all the teams in the organization.  You can only delete organizations that are associated with your current Make zone. Your current Make zone is specified in the API call URL. Currently, it is either:  - `eu1.make.com`  - `us1.make.com`&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithOrganizationItemRequestBuilderDeleteQueryParameters 
        {
            /// <summary>Set to `true` to confirm the organization deletion. Otherwise, if the organization has active scenarios, Make won&apos;t delete the organization and the API call returns an error.</summary>
            [QueryParameter("confirmed")]
            public bool? Confirmed { get; set; }
        }
        /// <summary>
        /// Retrieves detail information of the organization with the specified `organizationId`.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithOrganizationItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Set this parameter to `true` if you are using the API call `GET /organizations/{organizationId}` shortly after creating the organization. The API call will first check synchronization of the Make backend and your Make zone data. If you don&apos;t use this argument, the API call might fail with an error due to unfinished data synchronization. The default value of this argument is `false`.</summary>
            [QueryParameter("wait")]
            public bool? Wait { get; set; }
        }
    }
}
#pragma warning restore CS0618
