// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Make.OpenApiClient.ExecutionCapacity.Item.Live;
using Soenneker.Make.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Make.OpenApiClient.ExecutionCapacity.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \execution-capacity\{organizationId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithOrganizationItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The live property</summary>
        public global::Soenneker.Make.OpenApiClient.ExecutionCapacity.Item.Live.LiveRequestBuilder Live
        {
            get => new global::Soenneker.Make.OpenApiClient.ExecutionCapacity.Item.Live.LiveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.ExecutionCapacity.Item.WithOrganizationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOrganizationItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/execution-capacity/{organizationId}{?from*,rollupSeconds*,to*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.ExecutionCapacity.Item.WithOrganizationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOrganizationItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/execution-capacity/{organizationId}{?from*,rollupSeconds*,to*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns historical parallel execution usage metrics for an Organization over a time range, aggregated into samples at a fixed rollup interval. The sample with the highest capacity utilization is picked for each time interval.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetExecutionCapacityByOrganizationId200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Make.OpenApiClient.Models.GetExecutionCapacityByOrganizationId422Response">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetExecutionCapacityByOrganizationId200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.ExecutionCapacity.Item.WithOrganizationItemRequestBuilder.WithOrganizationItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetExecutionCapacityByOrganizationId200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.ExecutionCapacity.Item.WithOrganizationItemRequestBuilder.WithOrganizationItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Soenneker.Make.OpenApiClient.Models.GetExecutionCapacityByOrganizationId422Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.GetExecutionCapacityByOrganizationId200Response>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.GetExecutionCapacityByOrganizationId200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns historical parallel execution usage metrics for an Organization over a time range, aggregated into samples at a fixed rollup interval. The sample with the highest capacity utilization is picked for each time interval.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.ExecutionCapacity.Item.WithOrganizationItemRequestBuilder.WithOrganizationItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.ExecutionCapacity.Item.WithOrganizationItemRequestBuilder.WithOrganizationItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.ExecutionCapacity.Item.WithOrganizationItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Make.OpenApiClient.ExecutionCapacity.Item.WithOrganizationItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Make.OpenApiClient.ExecutionCapacity.Item.WithOrganizationItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns historical parallel execution usage metrics for an Organization over a time range, aggregated into samples at a fixed rollup interval. The sample with the highest capacity utilization is picked for each time interval.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithOrganizationItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Start of the time range (inclusive), as an ISO 8601 date-time</summary>
            [QueryParameter("from")]
            public DateTimeOffset? From { get; set; }
            /// <summary>Time interval in seconds used for rolling up the samples. When omitted, a rollup is chosen automatically so the sample count stays at constant size.</summary>
            [QueryParameter("rollupSeconds")]
            public int? RollupSeconds { get; set; }
            /// <summary>End of the time range (exclusive), as an ISO 8601 date-time</summary>
            [QueryParameter("to")]
            public DateTimeOffset? To { get; set; }
        }
    }
}
#pragma warning restore CS0618
