// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Make.OpenApiClient.Functions.Eval;
using Soenneker.Make.OpenApiClient.Functions.Item;
using Soenneker.Make.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Make.OpenApiClient.Functions
{
    /// <summary>
    /// Builds and executes requests for operations under \functions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FunctionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The eval property</summary>
        public global::Soenneker.Make.OpenApiClient.Functions.Eval.EvalRequestBuilder Eval
        {
            get => new global::Soenneker.Make.OpenApiClient.Functions.Eval.EvalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Make.OpenApiClient.functions.item collection</summary>
        /// <param name="position">The ID of the custom function.</param>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Functions.Item.WithFunctionItemRequestBuilder"/></returns>
        public global::Soenneker.Make.OpenApiClient.Functions.Item.WithFunctionItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("functionId", position);
                return new global::Soenneker.Make.OpenApiClient.Functions.Item.WithFunctionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Functions.FunctionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FunctionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/functions?teamId={teamId}{&cols*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Functions.FunctionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FunctionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/functions?teamId={teamId}{&cols*}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;Retrieves a list of custom functions available in the team. The response contains `id`, `name`, `description` and a brief updates history of all custom functions available in the team.Check availability of the custom functions feature with the API call `GET /organizations/{organizationId}` for the organization to which the team belongs. If the response contains `\&quot;customFunctions\&quot;: true` pair in the `license` object then you have access to the custom functions feature.Refer to the [Make pricing page](https://www.make.com/en/help/general/pricing-parameters) for Make pricing plans overview.&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.GetFunctions200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetFunctions200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Functions.FunctionsRequestBuilder.FunctionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.GetFunctions200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Functions.FunctionsRequestBuilder.FunctionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.GetFunctions200Response>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.GetFunctions200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Creates a custom function. Specify function `name`, `description` and `code` in the request body.You cannot use a JavaScript reserved word for the function `name`. Check the [list of JavaScript reserved words](https://www.w3schools.com/js/js_reserved.asp).Make sure to use the same function name in the `name` field and in the function&apos;s `code`. Otherwise, you get the IM005 error.Make validates the custom function&apos;s code first. You get an IM005 error if the code validation fails. The validation might fail because of a syntax error in the function&apos;s code or when the code uses a JavaScript feature that Make doesn&apos;t support. Check the [custom functions limitations](https://www.make.com/en/help/functions/custom-functions#limitations-of-custom-functions) in the Make Help center.Check availability of the custom functions feature with the API call `GET /organizations/{organizationId}` for the organization to which the team belongs. If the response contains `\&quot;customFunctions\&quot;: true` pair in the `license` object then you have access to the custom functions feature.Refer to the [Make pricing page](https://www.make.com/en/help/general/pricing-parameters) for Make pricing plans overview.&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.PostFunctions200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.PostFunctions200Response?> PostAsync(global::Soenneker.Make.OpenApiClient.Models.PostFunctionsRequest body, Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Functions.FunctionsRequestBuilder.FunctionsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.PostFunctions200Response> PostAsync(global::Soenneker.Make.OpenApiClient.Models.PostFunctionsRequest body, Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Functions.FunctionsRequestBuilder.FunctionsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.PostFunctions200Response>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.PostFunctions200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Retrieves a list of custom functions available in the team. The response contains `id`, `name`, `description` and a brief updates history of all custom functions available in the team.Check availability of the custom functions feature with the API call `GET /organizations/{organizationId}` for the organization to which the team belongs. If the response contains `\&quot;customFunctions\&quot;: true` pair in the `license` object then you have access to the custom functions feature.Refer to the [Make pricing page](https://www.make.com/en/help/general/pricing-parameters) for Make pricing plans overview.&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Functions.FunctionsRequestBuilder.FunctionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Functions.FunctionsRequestBuilder.FunctionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// &quot;Creates a custom function. Specify function `name`, `description` and `code` in the request body.You cannot use a JavaScript reserved word for the function `name`. Check the [list of JavaScript reserved words](https://www.w3schools.com/js/js_reserved.asp).Make sure to use the same function name in the `name` field and in the function&apos;s `code`. Otherwise, you get the IM005 error.Make validates the custom function&apos;s code first. You get an IM005 error if the code validation fails. The validation might fail because of a syntax error in the function&apos;s code or when the code uses a JavaScript feature that Make doesn&apos;t support. Check the [custom functions limitations](https://www.make.com/en/help/functions/custom-functions#limitations-of-custom-functions) in the Make Help center.Check availability of the custom functions feature with the API call `GET /organizations/{organizationId}` for the organization to which the team belongs. If the response contains `\&quot;customFunctions\&quot;: true` pair in the `license` object then you have access to the custom functions feature.Refer to the [Make pricing page](https://www.make.com/en/help/general/pricing-parameters) for Make pricing plans overview.&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Make.OpenApiClient.Models.PostFunctionsRequest body, Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Functions.FunctionsRequestBuilder.FunctionsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Make.OpenApiClient.Models.PostFunctionsRequest body, Action<RequestConfiguration<global::Soenneker.Make.OpenApiClient.Functions.FunctionsRequestBuilder.FunctionsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/functions?teamId={teamId}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Functions.FunctionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Make.OpenApiClient.Functions.FunctionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Make.OpenApiClient.Functions.FunctionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &quot;Retrieves a list of custom functions available in the team. The response contains `id`, `name`, `description` and a brief updates history of all custom functions available in the team.Check availability of the custom functions feature with the API call `GET /organizations/{organizationId}` for the organization to which the team belongs. If the response contains `\&quot;customFunctions\&quot;: true` pair in the `license` object then you have access to the custom functions feature.Refer to the [Make pricing page](https://www.make.com/en/help/general/pricing-parameters) for Make pricing plans overview.&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FunctionsRequestBuilderGetQueryParameters 
        {
            /// <summary>Specifies columns that are returned in the response. Use the `cols[]` parameter for every column that you want to return in the response. For example `GET /endpoint?cols[]=key1&amp;cols[]=key2` to get both `key1` and `key2` columns in the response.[Check the &quot;Filtering&quot; section for a full example.](/api-documentation/pagination-sorting-filtering/filtering)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cols")]
            public string[]? Cols { get; set; }
#nullable restore
#else
            [QueryParameter("cols")]
            public string[] Cols { get; set; }
#endif
            /// <summary>The ID of the team.</summary>
            [QueryParameter("teamId")]
            public int? TeamId { get; set; }
        }
        /// <summary>
        /// &quot;Creates a custom function. Specify function `name`, `description` and `code` in the request body.You cannot use a JavaScript reserved word for the function `name`. Check the [list of JavaScript reserved words](https://www.w3schools.com/js/js_reserved.asp).Make sure to use the same function name in the `name` field and in the function&apos;s `code`. Otherwise, you get the IM005 error.Make validates the custom function&apos;s code first. You get an IM005 error if the code validation fails. The validation might fail because of a syntax error in the function&apos;s code or when the code uses a JavaScript feature that Make doesn&apos;t support. Check the [custom functions limitations](https://www.make.com/en/help/functions/custom-functions#limitations-of-custom-functions) in the Make Help center.Check availability of the custom functions feature with the API call `GET /organizations/{organizationId}` for the organization to which the team belongs. If the response contains `\&quot;customFunctions\&quot;: true` pair in the `license` object then you have access to the custom functions feature.Refer to the [Make pricing page](https://www.make.com/en/help/general/pricing-parameters) for Make pricing plans overview.&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FunctionsRequestBuilderPostQueryParameters 
        {
            /// <summary>The ID of the team.</summary>
            [QueryParameter("teamId")]
            public int? TeamId { get; set; }
        }
    }
}
#pragma warning restore CS0618
