// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Make.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Make.OpenApiClient.Scenarios.MoveToTrash
{
    /// <summary>
    /// Builds and executes requests for operations under \scenarios\move-to-trash
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MoveToTrashRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Scenarios.MoveToTrash.MoveToTrashRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MoveToTrashRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/scenarios/move-to-trash", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Make.OpenApiClient.Scenarios.MoveToTrash.MoveToTrashRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MoveToTrashRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/scenarios/move-to-trash", rawUrl)
        {
        }
        /// <summary>
        /// Moves up to 1,000 scenarios of one team to the trash in a single request. Each scenario issoft-deleted the same way as `DELETE /scenarios/{scenarioId}`: an active scenario is stoppedfirst, and the scenario can be restored within the 30-day recovery window. The request is theconfirmation, so a scenario that other scenarios use as a subscenario or as a dead-letter queueis trashed without the confirmation prompt the single delete returns.Every requested id is processed on its own. An id that does not exist, belongs to another team,or is already in trash is reported in `rejectedScenarios` with `IM301`; a failure while trashingone scenario rejects only that scenario with the failure&apos;s code. The response is `200` even whenevery id was rejected. Larger selections must be split into several requests.Requires the `scenario delete` permission on the team.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Models.PostScenariosMoveToTrash200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Make.OpenApiClient.Models.PostScenariosMoveToTrash400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Make.OpenApiClient.Models.PostScenariosMoveToTrash401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Make.OpenApiClient.Models.PostScenariosMoveToTrash403Response">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Make.OpenApiClient.Models.PostScenariosMoveToTrash200Response?> PostAsync(global::Soenneker.Make.OpenApiClient.Models.PostScenariosMoveToTrashRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Make.OpenApiClient.Models.PostScenariosMoveToTrash200Response> PostAsync(global::Soenneker.Make.OpenApiClient.Models.PostScenariosMoveToTrashRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Make.OpenApiClient.Models.PostScenariosMoveToTrash400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Make.OpenApiClient.Models.PostScenariosMoveToTrash401Response.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Make.OpenApiClient.Models.PostScenariosMoveToTrash403Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Make.OpenApiClient.Models.PostScenariosMoveToTrash200Response>(requestInfo, global::Soenneker.Make.OpenApiClient.Models.PostScenariosMoveToTrash200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Moves up to 1,000 scenarios of one team to the trash in a single request. Each scenario issoft-deleted the same way as `DELETE /scenarios/{scenarioId}`: an active scenario is stoppedfirst, and the scenario can be restored within the 30-day recovery window. The request is theconfirmation, so a scenario that other scenarios use as a subscenario or as a dead-letter queueis trashed without the confirmation prompt the single delete returns.Every requested id is processed on its own. An id that does not exist, belongs to another team,or is already in trash is reported in `rejectedScenarios` with `IM301`; a failure while trashingone scenario rejects only that scenario with the failure&apos;s code. The response is `200` even whenevery id was rejected. Larger selections must be split into several requests.Requires the `scenario delete` permission on the team.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Make.OpenApiClient.Models.PostScenariosMoveToTrashRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Make.OpenApiClient.Models.PostScenariosMoveToTrashRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Make.OpenApiClient.Scenarios.MoveToTrash.MoveToTrashRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Make.OpenApiClient.Scenarios.MoveToTrash.MoveToTrashRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Make.OpenApiClient.Scenarios.MoveToTrash.MoveToTrashRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
